// packages/vue/src/panel/Panel.vue
<template>
  <div :class="cx('root')" :id="instanceId">
    <div v-if="showHeader" :class="cx('header', { toggleable })">
      <span v-if="header" :class="cx('title')" :id="headerId">{{ header }}</span>
      <slot name="header"></slot>
      <div :class="cx('headerActions')">
        <UButton
          v-if="toggleable"
          severity="secondary"
          text
          rounded
          type="button"
          :aria-controls="contentId"
          :aria-expanded="!d_collapsed"
          :icon="d_collapsed ? 'pi pi-plus' : 'pi pi-minus'"
          @click="toggle"
        />
      </div>
    </div>
    <div
      v-if="!toggleable || !d_collapsed"
      :class="cx('contentContainer')"
      role="region"
      :id="contentId"
      :aria-labelledby="headerId"
    >
      <div :class="cx('content')">
        <slot></slot>
      </div>
      <div v-if="$slots.footer" :class="cx('footer')">
        <slot name="footer"></slot>
      </div>
    </div>
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Panel` component (see
// .vendor-extracted/vue/panel/Panel.vue). Confirmed against real source:
// extends the bare `BaseComponent` tier (no v-model/writeValue) — a
// container with header/content/footer regions and an optional
// content-toggle feature, composing `UButton` for its toggle affordance
// (matching this batch's own `UButton` composition precedent from
// `USplitButton`), and following `UFieldset`'s own `d_collapsed`
// internal-state pattern exactly.
//
// Deliberately excludes real source's `icons`/custom header/footer
// template-override system and its `<transition name="p-collapsible">`
// collapse animation — same "smaller surface than upstream" precedent as
// every sibling component.
import { UButton } from "../button";
import { createBasePanel } from "./BasePanel";

let uid = 0;

export default {
  name: "UPanel",
  extends: createBasePanel(),
  inheritAttrs: false,
  components: { UButton },
  emits: ["update:collapsed", "before-toggle", "after-toggle"],
  data() {
    return {
      d_collapsed: this.collapsed,
      instanceId: `u_panel_${++uid}`,
    };
  },
  computed: {
    headerId() {
      return `${this.instanceId}_header`;
    },
    contentId() {
      return `${this.instanceId}_content`;
    },
  },
  watch: {
    collapsed(newValue) {
      this.d_collapsed = newValue;
    },
  },
  methods: {
    toggle(event) {
      this.$emit("before-toggle", { originalEvent: event, collapsed: this.d_collapsed });
      this.d_collapsed = !this.d_collapsed;
      this.$emit("update:collapsed", this.d_collapsed);
      this.$emit("after-toggle", { originalEvent: event, collapsed: this.d_collapsed });
    },
  },
};
</script>

// packages/react/src/panel/panel.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { UButton } from "../button";
import { panelStyleModule } from "./panel-style";

export interface UPanelProps {
  header?: React.ReactNode;
  toggleable?: boolean;
  collapsed?: boolean;
  showHeader?: boolean;
  onToggle?: (event: { originalEvent: React.SyntheticEvent; value: boolean }) => void;
  footer?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

let uid = 0;

/**
 * Ultimate-owned adaptation of PrimeReact's `Panel` component (real
 * source: `components/lib/panel/Panel.js`/`PanelBase.js`). Confirmed
 * against real source: extends the bare `ComponentBase` tier (no CVA) — a
 * container with header/content/footer regions and an optional content-
 * toggle feature, composing `Button` for its toggle affordance (matching
 * this batch's own `UButton` composition precedent from `USplitButton`).
 *
 * Uncontrolled by default (internal `collapsedState`), controlled when
 * `onToggle` is supplied — matching `UFieldset`'s own established
 * controlled/uncontrolled precedent in this codebase. Deliberately
 * excludes real source's `icons`/custom header/footer render-prop
 * overrides (only `header`/`footer` React-node props are offered) and its
 * `CSSTransition`-driven collapse animation — same "smaller surface than
 * upstream" precedent as every sibling component.
 */
export const UPanel = React.forwardRef<HTMLDivElement, UPanelProps>(function UPanel(
  {
    header,
    toggleable = false,
    collapsed: collapsedProp = false,
    showHeader = true,
    onToggle,
    footer,
    children,
    className,
  },
  ref
) {
  const { cx } = useComponentBase({ componentName: "panel", styleModule: panelStyleModule });
  const [collapsedState, setCollapsedState] = React.useState(collapsedProp);
  const collapsed = onToggle ? collapsedProp : collapsedState;

  const idRef = React.useRef<string>();
  if (!idRef.current) {
    idRef.current = `u_panel_${++uid}`;
  }
  const headerId = `${idRef.current}_header`;
  const contentId = `${idRef.current}_content`;

  const toggle = (event: React.SyntheticEvent) => {
    const next = !collapsed;
    if (!onToggle) {
      setCollapsedState(next);
    }
    onToggle?.({ originalEvent: event, value: next });
  };

  return (
    <div ref={ref} className={[cx("root"), className].filter(Boolean).join(" ")}>
      {showHeader && (
        <div className={cx("header", { toggleable })}>
          {header && (
            <span className={cx("title")} id={headerId}>
              {header}
            </span>
          )}
          <div className={cx("headerActions")}>
            {toggleable && (
              <UButton
                severity="secondary"
                text
                rounded
                type="button"
                aria-controls={contentId}
                aria-expanded={!collapsed}
                icon={<i className={collapsed ? "pi pi-plus" : "pi pi-minus"} />}
                onClick={toggle}
              />
            )}
          </div>
        </div>
      )}
      {(!toggleable || !collapsed) && (
        <div className={cx("contentContainer")} role="region" id={contentId} aria-labelledby={headerId}>
          <div className={cx("content")}>{children}</div>
          {footer && <div className={cx("footer")}>{footer}</div>}
        </div>
      )}
    </div>
  );
});
