// packages/vue/src/organization-chart/OrganizationChart.vue
<script>
import { h } from "vue";
import { createBaseOrganizationChart } from "./BaseOrganizationChart";

export default {
  name: "UOrganizationChart",
  extends: createBaseOrganizationChart(),
  data() {
    return { localCollapsedKeys: { ...(this.collapsedKeys ?? {}) } };
  },
  watch: {
    collapsedKeys(value) {
      this.localCollapsedKeys = { ...(value ?? {}) };
    },
  },
  methods: {
    toggleCollapse(node) {
      if (!this.collapsible || node.key == null) return;
      const keys = { ...this.localCollapsedKeys };
      if (keys[node.key]) delete keys[node.key];
      else keys[node.key] = true;
      this.localCollapsedKeys = keys;
      this.$emit("update:collapsedKeys", keys);
    },
    toggleSelect(node) {
      if (!this.selectionMode || node.selectable === false || node.key == null) return;
      let keys = { ...(this.selectionKeys ?? {}) };
      if (keys[node.key]) delete keys[node.key];
      else {
        if (this.selectionMode === "single") keys = {};
        keys[node.key] = true;
      }
      this.$emit("update:selectionKeys", keys);
    },
    renderNode(node) {
      if (!node) return null;
      const children = node.children ?? [];
      const expanded = !this.collapsible || !this.localCollapsedKeys[node.key];
      const selected = Boolean(this.selectionKeys?.[node.key]);
      return h(
        "div",
        {
          class: [this.cx("node"), node.className],
          role: "treeitem",
          "aria-expanded": children.length ? expanded : undefined,
          "aria-selected": this.selectionMode ? selected : undefined,
          "data-pc-section": "node",
          "data-selected": selected ? "true" : undefined,
        },
        [
          h(
            "div",
            {
              class: this.cx("nodeContent"),
              tabindex: this.selectionMode ? 0 : undefined,
              onClick: () => this.toggleSelect(node),
              onKeydown: (event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  this.toggleSelect(node);
                }
              },
            },
            [
              node.label,
              this.collapsible && children.length
                ? h(
                    "button",
                    {
                      type: "button",
                      "aria-label": "Toggle " + (node.label ?? "node"),
                      "aria-expanded": expanded,
                      onKeydown: (event) => event.stopPropagation(),
                      onClick: (event) => {
                        event.stopPropagation();
                        this.toggleCollapse(node);
                      },
                    },
                    [h("span", { "aria-hidden": "true" }, expanded ? "−" : "+")]
                  )
                : null,
            ]
          ),
          expanded && children.length
            ? h(
                "div",
                { class: this.cx("children"), role: "group" },
                children.map((child) => this.renderNode(child))
              )
            : null,
        ]
      );
    },
  },
  render() {
    return h(
      "div",
      {
        class: this.cx("root"),
        role: "tree",
        "aria-label": "Organization chart",
        "aria-multiselectable": this.selectionMode === "multiple",
      },
      [this.renderNode(this.value)]
    );
  },
};
</script>

// packages/react/src/organization-chart/organization-chart.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import type { SelectionMode } from "@ultimate/uix-data";
import { organizationChartStyleModule } from "./organization-chart-style";

export interface OrganizationChartNodeData {
  label?: string;
  className?: string;
  expanded?: boolean;
  selectable?: boolean;
  children?: OrganizationChartNodeData[];
}

export interface UOrganizationChartProps {
  value: OrganizationChartNodeData[];
  selectionMode?: SelectionMode;
  selection?: OrganizationChartNodeData | OrganizationChartNodeData[] | null;
  onSelectionChange?: (
    selection: OrganizationChartNodeData | OrganizationChartNodeData[] | null
  ) => void;
  className?: string;
}

function OrganizationChartNode({
  node,
  selectionMode,
  selection,
  onSelectionChange,
  cx,
}: {
  node: OrganizationChartNodeData;
  selectionMode?: SelectionMode;
  selection?: UOrganizationChartProps["selection"];
  onSelectionChange?: UOrganizationChartProps["onSelectionChange"];
  cx: (key: string) => string | undefined;
}): React.ReactElement {
  const [expanded, setExpanded] = React.useState(node.expanded ?? false);
  const isSelected =
    selectionMode === "single"
      ? selection === node
      : Array.isArray(selection) && selection.includes(node);

  const handleSelect = (): void => {
    if (!selectionMode || !onSelectionChange || node.selectable === false) return;
    if (selectionMode === "single") {
      onSelectionChange(selection === node ? null : node);
    } else {
      const current = Array.isArray(selection) ? selection : [];
      onSelectionChange(
        current.includes(node) ? current.filter((n) => n !== node) : [...current, node]
      );
    }
  };

  return (
    <div
      className={[cx("node"), node.className].filter(Boolean).join(" ")}
      role="treeitem"
      aria-expanded={node.children?.length ? expanded : undefined}
      aria-selected={selectionMode ? isSelected : undefined}
    >
      <div
        className={cx("nodeContent")}
        data-selected={isSelected || undefined}
        tabIndex={selectionMode ? 0 : undefined}
        onClick={handleSelect}
        onKeyDown={(event) => {
          if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            handleSelect();
          }
        }}
      >
        {node.label}
        {node.children && node.children.length > 0 && (
          <button
            type="button"
            aria-label={"Toggle " + (node.label ?? "node")}
            aria-expanded={expanded}
            onKeyDown={(event) => event.stopPropagation()}
            onClick={(event) => {
              event.stopPropagation();
              setExpanded((e) => !e);
            }}
          >
            {expanded ? "-" : "+"}
          </button>
        )}
      </div>
      {expanded && node.children && node.children.length > 0 && (
        <div className={cx("children")} role="group">
          {node.children.map((child, index) => (
            <OrganizationChartNode
              key={index}
              node={child}
              selectionMode={selectionMode}
              selection={selection}
              onSelectionChange={onSelectionChange}
              cx={cx}
            />
          ))}
        </div>
      )}
    </div>
  );
}

export function UOrganizationChart({
  value,
  selectionMode,
  selection,
  onSelectionChange,
  className,
}: UOrganizationChartProps): React.ReactElement {
  const { cx } = useComponentBase({
    componentName: "organization-chart",
    styleModule: organizationChartStyleModule,
  });
  return (
    <div
      className={cx("root") + (className ? ` ${className}` : "")}
      role="tree"
      aria-label="Organization chart"
      aria-multiselectable={selectionMode === "multiple"}
    >
      {value.map((node, index) => (
        <OrganizationChartNode
          key={index}
          node={node}
          selectionMode={selectionMode}
          selection={selection}
          onSelectionChange={onSelectionChange}
          cx={cx}
        />
      ))}
    </div>
  );
}
