// packages/vue/src/select-button/SelectButton.vue
<template>
  <div :class="cx('root', { fluid: false })" role="group" :aria-labelledby="ariaLabelledby">
    <UToggleButton
      v-for="(option, index) in options"
      :key="getOptionLabel(option) + '_' + index"
      :model-value="isSelected(option)"
      :on-label="getOptionLabel(option)"
      :off-label="getOptionLabel(option)"
      :disabled="disabled || isOptionDisabled(option)"
      @update:model-value="onOptionSelect(option)"
    />
  </div>
</template>

<script>
import UToggleButton from "../toggle-button/ToggleButton.vue";
import { createBaseSelectButton } from "./BaseSelectButton";

// Real PrimeVue SelectButton (.vendor-extracted/vue/selectbutton/SelectButton.vue)
// renders a flat group of ToggleButton per option — NOT overlay-based, no
// panel/dropdown. This port composes UToggleButton (packages/vue/src/toggle-button)
// the same way, matching real source's own per-option composition exactly.
//
// Supports single-select (multiple=false, default — value is the selected
// option's value or null) and multi-select (multiple=true — value is an
// array), matching real source's own isSelected/onOptionSelect multiple
// branch. allowEmpty (default true) mirrors real source's own default.
//
// Deliberately excludes real source's much larger surface: dataKey-based
// equality, item slot templates, tabindex roving-focus management,
// passthrough — matching every sibling component's established "smaller
// surface than upstream" precedent.
export default {
  name: "USelectButton",
  extends: createBaseSelectButton(),
  components: { UToggleButton },
  emits: ["change"],
  methods: {
    getOptionLabel(option) {
      if (typeof this.optionLabel === "function") return this.optionLabel(option);
      if (typeof this.optionLabel === "string" && typeof option === "object" && option !== null) {
        return String(option[this.optionLabel] ?? "");
      }
      return String(option);
    },
    getOptionValue(option) {
      if (typeof this.optionValue === "function") return this.optionValue(option);
      if (typeof this.optionValue === "string" && typeof option === "object" && option !== null) {
        return option[this.optionValue];
      }
      return option;
    },
    isOptionDisabled(option) {
      if (typeof this.optionDisabled === "function") return this.optionDisabled(option);
      if (typeof this.optionDisabled === "string" && typeof option === "object" && option !== null) {
        return !!option[this.optionDisabled];
      }
      return false;
    },
    isSelected(option) {
      const optionValue = this.getOptionValue(option);
      if (this.multiple) {
        return Array.isArray(this.dValue) && this.dValue.some((v) => v === optionValue);
      }
      return this.dValue === optionValue;
    },
    onOptionSelect(option) {
      if (this.disabled || this.isOptionDisabled(option)) return;
      const optionValue = this.getOptionValue(option);
      const selected = this.isSelected(option);

      let newValue;
      if (this.multiple) {
        const current = Array.isArray(this.dValue) ? [...this.dValue] : [];
        if (selected) {
          if (!this.allowEmpty && current.length === 1) return;
          newValue = current.filter((v) => v !== optionValue);
        } else {
          newValue = [...current, optionValue];
        }
      } else {
        if (selected) {
          if (!this.allowEmpty) return;
          newValue = null;
        } else {
          newValue = optionValue;
        }
      }

      this.writeValue(newValue);
      this.$emit("change", { originalEvent: new Event("change"), value: newValue });
    },
  },
};
</script>

// packages/react/src/select-button/select-button.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { UToggleButton } from "../toggle-button/toggle-button";
import { selectButtonStyleModule } from "./select-button-style";

export interface USelectButtonChangeEvent<T = unknown> {
  originalEvent: React.SyntheticEvent;
  value: T;
}

export interface USelectButtonProps<T = unknown> {
  value: T;
  onChange: (event: USelectButtonChangeEvent<T>) => void;
  options: unknown[];
  optionLabel?: string | ((item: unknown) => string);
  optionValue?: string | ((item: unknown) => unknown);
  optionDisabled?: string | ((item: unknown) => boolean);
  multiple?: boolean;
  allowEmpty?: boolean;
  disabled?: boolean;
  className?: string;
  "aria-labelledby"?: string;
}

function resolve<R>(
  accessor: string | ((item: unknown) => R) | undefined,
  option: unknown,
  fallback: (option: unknown) => R
): R {
  if (typeof accessor === "function") {
    return accessor(option);
  }
  if (typeof accessor === "string" && typeof option === "object" && option !== null) {
    return (option as Record<string, unknown>)[accessor] as R;
  }
  return fallback(option);
}

/**
 * Ultimate-owned adaptation of PrimeReact's `SelectButton` (real source:
 * `components/lib/selectbutton/SelectButton.js`/`SelectButtonBase.js`,
 * extracted this session via `scripts/provenance/extract-primereact-source.mjs`).
 * Fully controlled (`value`/`onChange`), per React's established no-shared-
 * form-state-base-class convention — same shape every sibling React
 * component in this batch follows.
 *
 * NOT overlay-based — real source renders a flat group of
 * `SelectButtonItem` buttons (`props.options.map(...)`), no panel/dropdown.
 * This port composes `UToggleButton` (`../toggle-button/toggle-button.tsx`)
 * for each option, matching real source's own per-option button composition
 * (real source's own `SelectButtonItem` wraps a native button rather than
 * `ToggleButton`, but the "one interactive element per option, no overlay"
 * shape is the same — this port reuses the sibling `UToggleButton` already
 * built in this batch rather than hand-rolling a second button primitive).
 *
 * Supports both single-select (`multiple` false, default — `value` is the
 * selected option's value, or `null`) and multi-select (`multiple` true —
 * `value` is an array of selected option values), matching real source's own
 * `onOptionClick`/`isSelected` `multiple` branch exactly. `allowEmpty`
 * (default `true`) mirrors real source's own default.
 *
 * Deliberately excludes real source's much larger surface: `dataKey`-based
 * equality, `tooltip`/`tooltipOptions`, item template render props
 * (`itemTemplate`), and PrimeReact's global `context` config lookup —
 * matching every sibling component's established "smaller surface than
 * upstream" precedent.
 */
export function USelectButton<T = unknown>({
  value,
  onChange,
  options,
  optionLabel,
  optionValue,
  optionDisabled,
  multiple = false,
  allowEmpty = true,
  disabled = false,
  className,
  "aria-labelledby": ariaLabelledBy,
}: USelectButtonProps<T>): React.ReactElement {
  const { cx } = useComponentBase({ componentName: "select-button", styleModule: selectButtonStyleModule });

  const getOptionLabel = (option: unknown): string =>
    resolve(optionLabel, option, (o) => String(o));
  const getOptionValue = (option: unknown): unknown => resolve(optionValue, option, (o) => o);
  const isOptionDisabled = (option: unknown): boolean =>
    resolve(optionDisabled, option, () => false);

  const isSelected = (option: unknown): boolean => {
    const optionVal = getOptionValue(option);
    if (multiple) {
      return Array.isArray(value) && (value as unknown[]).some((v) => v === optionVal);
    }
    return value === optionVal;
  };

  const handleOptionClick = (event: React.SyntheticEvent, option: unknown) => {
    if (disabled || isOptionDisabled(option)) {
      return;
    }
    const optionVal = getOptionValue(option);
    const selected = isSelected(option);

    let newValue: unknown;
    if (multiple) {
      const current = Array.isArray(value) ? [...(value as unknown[])] : [];
      if (selected) {
        if (!allowEmpty && current.length === 1) {
          return;
        }
        newValue = current.filter((v) => v !== optionVal);
      } else {
        newValue = [...current, optionVal];
      }
    } else {
      if (selected) {
        if (!allowEmpty) {
          return;
        }
        newValue = null;
      } else {
        newValue = optionVal;
      }
    }

    onChange({ originalEvent: event, value: newValue as T });
  };

  return (
    <div
      role="group"
      aria-labelledby={ariaLabelledBy}
      className={[cx("root", { fluid: false }), className].filter(Boolean).join(" ")}
    >
      {options.map((option, index) => {
        const label = getOptionLabel(option);
        return (
          <UToggleButton
            key={`${label}_${index}`}
            checked={isSelected(option)}
            onChange={(event) => handleOptionClick(event.originalEvent, option)}
            onLabel={label}
            offLabel={label}
            disabled={disabled || isOptionDisabled(option)}
          />
        );
      })}
    </div>
  );
}
