// packages/vue/src/message/Message.vue
<template>
  <div v-if="visible" :class="cx('root', { severity })" role="alert" aria-live="polite" :data-severity="severity">
    <div :class="cx('content')">
      <span v-if="resolvedIcon" :class="cx('icon')">
        <i :class="resolvedIcon" aria-hidden="true"></i>
      </span>
      <span :class="cx('text')">
        <slot></slot>
      </span>
      <button
        v-if="closable"
        type="button"
        :class="cx('closeButton')"
        :aria-label="closeAriaLabel"
        @click="close($event)"
      >
        <i v-if="closeIcon" :class="closeIcon" aria-hidden="true"></i>
        <template v-else>&times;</template>
      </button>
    </div>
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Message` component (see
// .vendor-extracted/vue/message/Message.vue). Confirmed against real
// source (all 3 frameworks): extends the bare `BaseComponent` tier (no
// v-model/writeValue) — a status/display component (severity-colored
// banner with an optional close button and optional auto-dismiss timer),
// never a form control.
//
// Real PrimeVue's own `Message` auto-selects a default icon per severity
// when no `icon` prop is given — this port keeps that behavior with plain
// `pi pi-*` icon classes. Deliberately excludes real source's
// `<transition>`-driven show/hide animation (plain `v-if` instead) and its
// `container`/`closeicon` slot-override system — same "smaller surface
// than upstream" precedent as every sibling component.
import { createBaseMessage } from "./BaseMessage";

const DEFAULT_ICON_CLASS = {
  info: "pi pi-info-circle",
  success: "pi pi-check",
  warn: "pi pi-exclamation-triangle",
  error: "pi pi-times-circle",
};

export default {
  name: "UMessage",
  extends: createBaseMessage(),
  inheritAttrs: false,
  emits: ["close"],
  data() {
    return {
      visible: true,
    };
  },
  computed: {
    resolvedIcon() {
      return this.icon ?? DEFAULT_ICON_CLASS[this.severity] ?? null;
    },
  },
  mounted() {
    if (this.life) {
      this.autoCloseTimer = setTimeout(() => {
        this.visible = false;
      }, this.life);
    }
  },
  beforeUnmount() {
    if (this.autoCloseTimer) clearTimeout(this.autoCloseTimer);
  },
  methods: {
    close(event) {
      this.visible = false;
      this.$emit("close", { originalEvent: event });
    },
  },
};
</script>

// packages/react/src/message/message.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { messageStyleModule } from "./message-style";

export interface UMessageProps {
  severity?: "success" | "info" | "warn" | "error" | "secondary" | "contrast";
  closable?: boolean;
  icon?: React.ReactNode;
  closeIcon?: React.ReactNode;
  life?: number;
  closeAriaLabel?: string;
  onClose?: (event: { originalEvent: React.SyntheticEvent }) => void;
  children?: React.ReactNode;
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `Message` component (real
 * source: `components/lib/message/Message.js`/`MessageBase.js`). Confirmed
 * against real source: extends the bare `ComponentBase` tier (no CVA) — a
 * status/display component (severity-colored banner with an optional close
 * button and optional auto-dismiss timer), never a form control.
 *
 * Real PrimeReact's own `Message` auto-selects a default icon per severity
 * (info/warn/error/success) when no `icon` prop is given — this port keeps
 * that behavior with plain `pi pi-*` icon classes (no bundled SVG icon
 * components exist in `react-core` yet for these 4 glyphs), disclosed
 * rather than silently omitted. Deliberately excludes real source's
 * `content` render-prop override and `pt`/passthrough system — same
 * "smaller surface than upstream" precedent as every sibling component.
 */
export const UMessage = React.forwardRef<HTMLDivElement, UMessageProps>(function UMessage(
  {
    severity = "info",
    closable = false,
    icon,
    closeIcon,
    life,
    closeAriaLabel = "Close",
    onClose,
    children,
    className,
  },
  ref
) {
  const { cx } = useComponentBase({ componentName: "message", styleModule: messageStyleModule });
  const [visible, setVisible] = React.useState(true);

  React.useEffect(() => {
    if (!life) return;
    const timer = setTimeout(() => setVisible(false), life);
    return () => clearTimeout(timer);
  }, [life]);

  const close = (event: React.SyntheticEvent) => {
    setVisible(false);
    onClose?.({ originalEvent: event });
  };

  const defaultIconClass: Record<string, string> = {
    info: "pi pi-info-circle",
    success: "pi pi-check",
    warn: "pi pi-exclamation-triangle",
    error: "pi pi-times-circle",
  };
  const resolvedIcon = icon ?? (defaultIconClass[severity] ? <i className={defaultIconClass[severity]} aria-hidden="true" /> : null);

  if (!visible) return null;

  return (
    <div
      ref={ref}
      className={[cx("root", { severity }), className].filter(Boolean).join(" ")}
      role="alert"
      aria-live="polite"
      data-severity={severity}
    >
      <div className={cx("content")}>
        {resolvedIcon && <span className={cx("icon")}>{resolvedIcon}</span>}
        <span className={cx("text")}>{children}</span>
        {closable && (
          <button
            type="button"
            className={cx("closeButton")}
            aria-label={closeAriaLabel}
            onClick={close}
          >
            {closeIcon ?? <>&times;</>}
          </button>
        )}
      </div>
    </div>
  );
});
