// packages/vue/src/confirm-dialog/ConfirmDialog.vue
<template>
  <UDialog
    :visible="visible"
    :header="confirmation?.header"
    :modal="confirmation?.modal ?? true"
    :closeOnEscape="confirmation?.closeOnEscape ?? true"
    :class="cx('root')"
    @update:visible="onDialogVisibleChange"
  >
    <i v-if="confirmation?.icon" :class="[confirmation.icon, cx('icon')]" />
    <span :class="cx('message')">{{ confirmation?.message }}</span>
    <template #footer>
      <div :class="cx('footer')">
        <button
          v-if="confirmation?.rejectVisible !== false"
          type="button"
          @click="onReject"
        >
          {{ confirmation?.rejectLabel ?? "No" }}
        </button>
        <button
          v-if="confirmation?.acceptVisible !== false"
          type="button"
          @click="onAccept"
        >
          {{ confirmation?.acceptLabel ?? "Yes" }}
        </button>
      </div>
    </template>
  </UDialog>
</template>

<script>
import { confirmationEventBus } from "@ultimate/vue-core";
import UDialog from "../dialog/Dialog.vue";
import { createBaseConfirmDialog } from "./BaseConfirmDialog";

// Ultimate-owned adaptation of PrimeVue's `ConfirmDialog` component (see
// .vendor-extracted/vue/confirmdialog/ConfirmDialog.vue). Confirmed against
// real source: ConfirmDialog subscribes to `ConfirmationEventBus`'s
// 'confirm'/'close' events (real source's own module-level singleton event
// bus, matching this task's own vue-core `confirmationEventBus` exactly —
// same primitive, not a reinvented mechanism) and renders itself (via a
// composed Dialog) whenever a confirmation matching its own `group` arrives.
//
// This port keeps that same real mechanism, composing the already-Built
// UDialog the same way real upstream composes Dialog.
export default {
  name: "UConfirmDialog",
  extends: createBaseConfirmDialog(),
  data() {
    return {
      confirmation: null,
    };
  },
  computed: {
    visible() {
      return this.confirmation !== null;
    },
  },
  confirmListener: null,
  closeListener: null,
  mounted() {
    this.confirmListener = (options) => {
      if (options && options.key === this.group) {
        this.confirmation = options;
      }
    };
    this.closeListener = () => {
      this.confirmation = null;
    };
    confirmationEventBus.on("confirm", this.confirmListener);
    confirmationEventBus.on("close", this.closeListener);
  },
  beforeUnmount() {
    confirmationEventBus.off("confirm", this.confirmListener);
    confirmationEventBus.off("close", this.closeListener);
  },
  methods: {
    hide() {
      this.confirmation = null;
    },
    onAccept() {
      this.confirmation?.accept?.();
      this.hide();
    },
    onReject() {
      this.confirmation?.reject?.();
      this.hide();
    },
    onDialogVisibleChange(value) {
      if (!value) this.hide();
    },
  },
  components: { UDialog },
};
</script>

// packages/react/src/confirm-dialog/confirm-dialog.tsx
import * as React from "react";
import { useComponentBase, confirmationEventBus, type UConfirmationOptions } from "@ultimate/react-core";
import { UButton } from "../button/button";
import { UDialog } from "../dialog/dialog";
import { confirmDialogStyleModule } from "./confirm-dialog-style";

export interface UConfirmDialogProps {
  /** Matches only `confirmDialog()` calls carrying the same `group` (undefined matches undefined) — matching real PrimeReact's own `group` field. */
  group?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `ConfirmDialog` component (real
 * source: `components/lib/confirmdialog/ConfirmDialog.js`). Confirmed
 * against real source: `ConfirmDialog` is a service-driven overlay — it
 * subscribes to `OverlayService`'s `confirm-dialog` event (via
 * `OverlayService.on('confirm-dialog', confirm)`) and renders itself (via
 * a composed `Dialog`) whenever the event's `group` matches its own,
 * invoking `accept`/`reject` callbacks from its own accept/reject button
 * handlers.
 *
 * This port keeps that same real mechanism, using this task's own
 * `confirmationEventBus`/`confirmDialog()` (`@ultimate/react-core` — new
 * for React this task, see that module's own doc comment) in place of real
 * PrimeReact's `OverlayService`, and composes the already-Built `UDialog`
 * the same way real upstream composes `Dialog`.
 *
 * Deliberately excludes upstream's much larger surface — draggable,
 * breakpoints-driven responsive `<style>`, custom footer/message/icon
 * render-prop templates, and RTL — none of these appear in this
 * capability's spec-mandated surface. A single always-mounted
 * `UConfirmDialog` per `group` is the expected usage, matching real
 * upstream's own single-instance-per-group convention.
 */
export function UConfirmDialog({ group }: UConfirmDialogProps): React.ReactNode {
  const { cx } = useComponentBase({
    componentName: "confirm-dialog",
    styleModule: confirmDialogStyleModule,
  });
  const [confirmation, setConfirmation] = React.useState<UConfirmationOptions | null>(null);

  React.useEffect(() => {
    const handler = (event: unknown) => {
      const options = event as UConfirmationOptions;
      if (options.visible === false) {
        setConfirmation(null);
        return;
      }
      if (options.group === group) {
        setConfirmation(options);
      }
    };
    confirmationEventBus.on("confirm-dialog", handler);
    return () => confirmationEventBus.off("confirm-dialog", handler);
  }, [group]);

  const hide = () => setConfirmation(null);

  const onAccept = () => {
    confirmation?.accept?.();
    hide();
  };

  const onReject = () => {
    confirmation?.reject?.();
    hide();
  };

  return (
    <UDialog
      visible={confirmation !== null}
      onHide={hide}
      header={confirmation?.header}
      modal={confirmation?.modal ?? true}
      closeOnEscape={confirmation?.closeOnEscape ?? true}
      className={cx("root")}
      footer={
        <div className={cx("footer")}>
          {confirmation?.rejectVisible !== false && (
            <UButton label={confirmation?.rejectLabel ?? "No"} severity="secondary" text onClick={onReject} />
          )}
          {confirmation?.acceptVisible !== false && (
            <UButton label={confirmation?.acceptLabel ?? "Yes"} onClick={onAccept} />
          )}
        </div>
      }
    >
      {confirmation?.icon}
      <span className={cx("message")}>{confirmation?.message}</span>
    </UDialog>
  );
}
