// packages/vue/src/split-button/SplitButton.vue
<template>
  <div :class="cx('root')">
    <UButton
      :class="cx('pcButton')"
      :label="label"
      :icon="icon"
      :icon-pos="iconPos"
      :severity="severity"
      :text="text"
      :outlined="outlined"
      :size="size"
      :disabled="disabled"
      @click="onDefaultButtonClick"
    />
    <UButton
      ref="dropdownButton"
      :class="cx('pcDropdown')"
      icon="pi pi-chevron-down"
      :severity="severity"
      :text="text"
      :outlined="outlined"
      :size="size"
      :disabled="disabled"
      aria-haspopup="menu"
      @click="onDropdownButtonClick"
    />
    <UMenu ref="menu" :model="menuModel" :popup="true" @show="$emit('show')" @hide="$emit('hide')" />
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `SplitButton` component (see
// `.vendor-extracted/vue/splitbutton/SplitButton.vue`). Renders a default
// command button attached to a dropdown-toggle button, which opens a
// popup `Menu` of secondary commands.
//
// Real PrimeVue's `SplitButton` composes `Button` + `TieredMenu`
// (verified this task's Step 1 — `SplitButton.vue` imports
// `primevue/tieredmenu`, not `primevue/menu`), since upstream's own
// secondary items may themselves have nested `items`. This task's binding
// instruction (implementation-plan §5, Task Group C table) is explicit:
// SplitButton "composes already-Built Button + Menu — no dependency wait
// needed, both already exist" — so this adaptation composes Ultimate's
// own already-Built `UButton` + `UMenu` (in `popup` mode) directly, not
// `UTieredMenu` (itself one of this same batch's own new capabilities,
// not the plan's stated dependency) — same binding choice this task's
// Angular `USplitButton`/React `split-button.tsx` siblings already made
// for this same capability.
//
// `UMenu` (read-only reference, already Built) exposes no event for item
// selection — it only ever invokes each item's own `command` callback
// directly. `menuModel` below wraps every item's own `command` so the
// popup closes after any item is chosen, without modifying `UMenu` itself.
import { createBaseSplitButton } from "./BaseSplitButton";
import { UButton } from "../button";
import { UMenu } from "../menu";

export default {
  name: "USplitButton",
  extends: createBaseSplitButton(),
  inheritAttrs: false,
  emits: ["click", "show", "hide"],
  components: { UButton, UMenu },
  computed: {
    menuModel() {
      return this.model.map((item) => ({
        ...item,
        command: (event) => {
          this.$refs.menu.hide();
          if (item.command) item.command(event);
        },
      }));
    },
  },
  methods: {
    onDefaultButtonClick(event) {
      if (this.$refs.menu.overlayVisible) {
        this.$refs.menu.hide();
      }
      this.$emit("click", event);
    },
    onDropdownButtonClick(event) {
      this.$refs.menu.toggle(event, this.$refs.dropdownButton.$el);
    },
  },
};
</script>

// packages/react/src/split-button/split-button.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { UButton } from "../button";
import { UMenu, type UMenuHandle, type UMenuItem } from "../menu";
import { splitButtonStyleModule } from "./split-button-style";

export interface USplitButtonProps {
  /** MenuModel instance to define the overlay items. */
  model?: UMenuItem[];
  /** Text of the button. */
  label?: string;
  /** Name of the icon. */
  icon?: React.ReactNode;
  /** Position of the icon. */
  iconPos?: "left" | "right" | "top" | "bottom";
  /** Defines the style of the button. */
  severity?: "secondary" | "success" | "info" | "warning" | "danger" | "help" | "contrast";
  /** Add a textual class to the button without a background initially. */
  text?: boolean;
  /** Add a border class without a background initially. */
  outlined?: boolean;
  /** Defines the size of the button. */
  size?: "small" | "large";
  /** When present, it specifies that the component should be disabled. */
  disabled?: boolean;
  /** Callback to execute when the default command button is clicked. */
  onClick?: (event: React.SyntheticEvent) => void;
  /** Callback to execute when the popup menu is shown. */
  onShow?: () => void;
  /** Callback to execute when the popup menu is hidden. */
  onHide?: () => void;
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `SplitButton` component (see
 * `.vendor-extracted/react/splitbutton/SplitButton.js`). Renders a default
 * command button attached to a dropdown-toggle button, which opens a
 * popup `Menu` of secondary commands.
 *
 * Real PrimeReact's `SplitButton` composes `Button` + `TieredMenu`
 * (verified this task's Step 1 — `SplitButton.js` imports `../tieredmenu`,
 * not `../menu`), since upstream's own secondary items may themselves have
 * nested `items`. This task's binding instruction (implementation-plan §5,
 * Task Group C table) is explicit: SplitButton "composes already-Built
 * Button + Menu — no dependency wait needed, both already exist" — so this
 * adaptation composes Ultimate's own already-Built `UButton` + `UMenu`
 * (in `popup` mode) directly, not `UTieredMenu` (itself one of this same
 * batch's own new capabilities, not the plan's stated dependency).
 *
 * `UMenu`'s own popup mode already closes itself on outside click/Escape/
 * item selection (its own established behavior, read-only reference) — no
 * additional wrapping is needed beyond wiring `UMenuHandle.toggle()`/
 * `hide()` to the dropdown/default buttons.
 */
export const USplitButton = React.forwardRef<HTMLDivElement, USplitButtonProps>(function USplitButton(
  { model = [], label, icon, iconPos, severity, text, outlined, size, disabled, onClick, onShow, onHide, className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "split-button", styleModule: splitButtonStyleModule });
  const menuRef = React.useRef<UMenuHandle>(null);

  const handleDefaultClick = (event: React.SyntheticEvent) => {
    menuRef.current?.hide();
    onClick?.(event);
  };

  const handleDropdownClick = (event: React.SyntheticEvent) => {
    menuRef.current?.toggle(event);
  };

  return (
    <div ref={ref} className={[cx("root"), className].filter(Boolean).join(" ")}>
      <UButton
        className={cx("button")}
        label={label}
        icon={icon}
        iconPos={iconPos}
        severity={severity}
        text={text}
        outlined={outlined}
        size={size}
        disabled={disabled}
        onClick={handleDefaultClick}
      />
      <UButton
        className={cx("dropdown")}
        icon="▾"
        severity={severity}
        text={text}
        outlined={outlined}
        size={size}
        disabled={disabled}
        aria-haspopup="menu"
        onClick={handleDropdownClick}
      />
      <UMenu ref={menuRef} model={model} popup onShow={onShow} onHide={onHide} />
    </div>
  );
});
