// packages/vue/src/steps/Steps.vue
<template>
  <nav :class="cx('root')">
    <ol :class="cx('list')" @keydown="onKeydown">
      <template v-for="(item, index) in model" :key="(item.label || '') + index">
        <li
          v-if="isVisible(item)"
          :class="cx('item', { active: isActive(index), disabled: isItemDisabled(item, index) })"
          :aria-current="isActive(index) ? 'step' : undefined"
        >
          <a
            :href="item.url || '#'"
            :class="cx('itemLink')"
            :tabindex="isItemDisabled(item, index) ? -1 : 0"
            :aria-disabled="isItemDisabled(item, index)"
            @click="onItemClick($event, item, index)"
          >
            <span :class="cx('itemNumber')">{{ index + 1 }}</span>
            <span v-if="item.label" :class="cx('itemLabel')">{{ item.label }}</span>
          </a>
        </li>
      </template>
    </ol>
  </nav>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Steps` component (see
// `.vendor-extracted/vue/steps/Steps.vue`). Renders a linear, read-only-
// by-default step *indicator* for a wizard workflow — distinct from
// `UStepper`, which is an interactive, content-switching component.
//
// Real PrimeVue's `Steps` (`extends BaseComponent`, no import of
// `primevue/menu`) is a standalone, independent component driven by a
// flat `model` array and an `activeStep`, not a composition of `Menu`.
//
// `d_activeStep` is derived directly from `this.activeStep` (the prop),
// matching the same "derive independently from props, not from a parent
// tier's `data()`" pattern this task's other Vue components follow.
import { createBaseSteps } from "./BaseSteps";

export default {
  name: "USteps",
  extends: createBaseSteps(),
  inheritAttrs: false,
  emits: ["select"],
  data() {
    return {
      d_activeStep: this.activeStep,
    };
  },
  watch: {
    activeStep(newValue) {
      this.d_activeStep = newValue;
    },
  },
  methods: {
    isVisible(item) {
      return item.visible !== false;
    },
    isActive(index) {
      return index === this.d_activeStep;
    },
    isItemDisabled(item, index) {
      return !!item.disabled || (this.readonly && index !== this.d_activeStep);
    },
    onKeydown(event) {
      const links = Array.from(this.$el.querySelectorAll("a"));
      if (links.length === 0) return;
      // `links` holds rendered items only; pair each with its model index so
      // `isItemDisabled` (which compares against the active step) stays correct.
      const rendered = this.model
        .map((item, modelIndex) => ({ item, modelIndex }))
        .filter(({ item }) => this.isVisible(item));
      const isEnabled = (index) => !this.isItemDisabled(rendered[index].item, rendered[index].modelIndex);
      const currentIndex = links.indexOf(document.activeElement);

      let targetIndex;
      switch (event.code) {
        case "ArrowRight":
          for (let i = currentIndex + 1; i < links.length; i++) {
            if (isEnabled(i)) {
              targetIndex = i;
              break;
            }
          }
          break;
        case "ArrowLeft":
          for (let i = currentIndex - 1; i >= 0; i--) {
            if (isEnabled(i)) {
              targetIndex = i;
              break;
            }
          }
          break;
        case "Home":
          targetIndex = links.findIndex((_, i) => isEnabled(i));
          break;
        case "End":
          for (let i = links.length - 1; i >= 0; i--) {
            if (isEnabled(i)) {
              targetIndex = i;
              break;
            }
          }
          break;
        default:
          return;
      }

      event.preventDefault();
      if (targetIndex !== undefined && targetIndex >= 0) {
        links[targetIndex].focus();
      }
    },
    onItemClick(event, item, index) {
      if (this.readonly || item.disabled) {
        event.preventDefault();
        return;
      }
      this.$emit("select", { originalEvent: event, item, index });
      if (item.command) item.command({ originalEvent: event, item, index });
      if (!item.url) {
        event.preventDefault();
      }
    },
  },
};
</script>

// packages/react/src/steps/steps.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { stepsStyleModule } from "./steps-style";
import type { UMenuItem } from "../menu";

export interface UStepsProps {
  /** An array of menu items. */
  model?: UMenuItem[];
  /** Index of the active item. */
  activeIndex?: number;
  /** Whether the items are clickable or not. */
  readonly?: boolean;
  /** Callback to invoke when the new step is selected. */
  onSelect?: (event: { originalEvent: React.SyntheticEvent; item: UMenuItem; index: number }) => void;
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `Steps` component (see
 * `.vendor-extracted/react/steps/Steps.js`). Renders a linear, read-only-
 * by-default step *indicator* for a wizard workflow — distinct from
 * `UStepper`, which is an interactive, content-switching component.
 *
 * Real PrimeReact's `Steps` (no import of `../menu`) is a standalone,
 * independent component driven by a flat `MenuItem[]` model and an
 * `activeIndex`, not a composition of `Menu`.
 */
export const USteps = React.forwardRef<HTMLElement, UStepsProps>(function USteps(
  { model = [], activeIndex = 0, readonly = true, onSelect, className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "steps", styleModule: stepsStyleModule });
  const listRef = React.useRef<HTMLOListElement>(null);

  const isItemDisabled = (item: UMenuItem, index: number) => !!item.disabled || (readonly && index !== activeIndex);

  const onKeyDown = (event: React.KeyboardEvent) => {
    const links = Array.from(listRef.current?.querySelectorAll("a") ?? []);
    if (links.length === 0) return;
    // `links` holds rendered items only; pair each with its model index so
    // `isItemDisabled` (which compares against `activeIndex`) stays correct.
    const rendered = model
      .map((item, modelIndex) => ({ item, modelIndex }))
      .filter(({ item }) => item.visible !== false);
    const isEnabled = (index: number) => !isItemDisabled(rendered[index].item, rendered[index].modelIndex);
    const currentIndex = links.indexOf(document.activeElement as HTMLAnchorElement);

    let targetIndex: number | undefined;
    switch (event.code) {
      case "ArrowRight":
        for (let i = currentIndex + 1; i < links.length; i++) {
          if (isEnabled(i)) {
            targetIndex = i;
            break;
          }
        }
        break;
      case "ArrowLeft":
        for (let i = currentIndex - 1; i >= 0; i--) {
          if (isEnabled(i)) {
            targetIndex = i;
            break;
          }
        }
        break;
      case "Home":
        targetIndex = links.findIndex((_, i) => isEnabled(i));
        break;
      case "End":
        for (let i = links.length - 1; i >= 0; i--) {
          if (isEnabled(i)) {
            targetIndex = i;
            break;
          }
        }
        break;
      default:
        return;
    }

    event.preventDefault();
    if (targetIndex !== undefined && targetIndex >= 0) {
      links[targetIndex].focus();
    }
  };

  const onItemClick = (event: React.MouseEvent, item: UMenuItem, index: number) => {
    if (readonly || item.disabled) {
      event.preventDefault();
      return;
    }
    onSelect?.({ originalEvent: event, item, index });
    item.command?.({ originalEvent: event, item });
    if (!item.url) {
      event.preventDefault();
    }
  };

  return (
    <nav ref={ref} className={[cx("root"), className].filter(Boolean).join(" ")}>
      <ol ref={listRef} className={cx("list")} onKeyDown={onKeyDown}>
        {model.map((item, index) => {
          if (item.visible === false) return null;
          const active = index === activeIndex;
          return (
            <li
              key={item.label ?? index}
              className={cx("item", { active, disabled: isItemDisabled(item, index) })}
              aria-current={active ? "step" : undefined}
            >
              <a
                href={item.url ?? "#"}
                className={cx("itemLink")}
                tabIndex={isItemDisabled(item, index) ? -1 : 0}
                aria-disabled={isItemDisabled(item, index)}
                onClick={(event) => onItemClick(event, item, index)}
              >
                <span className={cx("itemNumber")}>{index + 1}</span>
                {item.label && <span className={cx("itemLabel")}>{item.label}</span>}
              </a>
            </li>
          );
        })}
      </ol>
    </nav>
  );
});
