// packages/react/src/scroller/scroller.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { calculateLast, calculateNumItemsInViewport } from "@ultimate/uix-data";
import { scrollerStyleModule } from "./scroller-style";

export interface UScrollerContentOptions {
  items: { index: number; value: unknown }[];
  getItemOptions: (index: number) => {
    index: number;
    count: number;
    first: boolean;
    last: boolean;
    even: boolean;
    odd: boolean;
  };
  itemSize: number;
  loading: boolean;
}

export interface UScrollerProps {
  items: unknown[];
  itemSize: number;
  numToleratedItems?: number;
  disabled?: boolean;
  lazy?: boolean;
  loading?: boolean;
  onLazyLoad?: (event: { first: number; last: number }) => void;
  // Optional render-prop mirroring real PrimeReact's own `contentTemplate`
  // prop mechanism (VirtualScroller.js:729-748): when present, it is called
  // instead of the built-in per-item `.map()` rendering; when absent,
  // today's built-in rendering runs unchanged. Consumed by a future UTable.
  contentTemplate?: (options: UScrollerContentOptions) => React.ReactNode;
}

export interface UScrollerHandle {
  scrollTo: (options: ScrollToOptions) => void;
  scrollToIndex: (index: number, behavior?: ScrollBehavior) => void;
}

function getLast(items: unknown[], last = 0, isCols = false): number {
  if (!items) return 0;
  const liveLength = isCols ? items.length : items.length; // isCols branch unreachable in vertical-only scope (Global Constraints)
  return Math.min(liveLength, last);
}

export const UScroller = React.forwardRef<UScrollerHandle, UScrollerProps>((props, forwardedRef) => {
  const {
    items,
    itemSize,
    numToleratedItems: numToleratedItemsProp,
    disabled = false,
    lazy = false,
    loading,
    onLazyLoad,
    contentTemplate,
  } = props;
  const { cx } = useComponentBase({ componentName: "scroller", styleModule: scrollerStyleModule });

  const elementRef = React.useRef<HTMLDivElement>(null);

  const [contentSizeState, setContentSizeState] = React.useState(0);
  const [firstState, setFirstState] = React.useState(0);

  React.useImperativeHandle(forwardedRef, () => ({
    scrollTo: (options: ScrollToOptions) => elementRef.current?.scrollTo(options),
    scrollToIndex: (index: number, behavior: ScrollBehavior = "auto") =>
      elementRef.current?.scrollTo({ top: index * itemSize, behavior }),
  }));

  React.useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    // Measures the root viewport element's offsetHeight — matching real
    // PrimeReact's elementRef.current.offsetHeight measurement exactly
    // (VirtualScroller.js:186, pinned commit d0f574e39122668292fc7a740f081bae1b93b1e9),
    // not clientHeight.
    setContentSizeState(el.offsetHeight);
    const observer = new ResizeObserver(() => setContentSizeState(el.offsetHeight));
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  const numItemsInViewport = calculateNumItemsInViewport(contentSizeState, itemSize);
  // numToleratedItems is honored from day one — an explicit override always
  // takes effect, it is never silently hardcoded to a half-viewport default
  // regardless of what the caller passed.
  const numToleratedItems =
    numToleratedItemsProp !== undefined ? numToleratedItemsProp : Math.ceil(numItemsInViewport / 2);
  const rawLast = calculateLast(firstState, numItemsInViewport, numToleratedItems);
  const last = getLast(items, rawLast);

  const visibleItems = disabled
    ? items.map((value, index) => ({ index, value }))
    : Array.from({ length: Math.max(0, last - firstState) }, (_, i) => ({
        index: firstState + i,
        value: items[firstState + i],
      }));

  // Mirrors real PrimeReact's getOptions(index) shape, matching the same
  // real per-item metadata fields confirmed for Angular's Task 1.
  const getItemOptions = (index: number) => ({
    index,
    count: items.length,
    first: index === 0,
    last: index === items.length - 1,
    even: index % 2 === 0,
    odd: index % 2 !== 0,
  });

  const handleScroll = () => {
    const el = elementRef.current;
    if (!el) return;
    const newFirst = Math.floor(el.scrollTop / (itemSize || 1));
    if (newFirst !== firstState) {
      setFirstState(newFirst);
      if (lazy && onLazyLoad) {
        const first = newFirst;
        const currentLast = getLast(items, calculateLast(first, numItemsInViewport, numToleratedItems));
        Promise.resolve().then(() => onLazyLoad({ first, last: currentLast }));
      }
    }
  };

  return (
    <div
      ref={elementRef}
      className={cx("root") as string}
      data-num-items-in-viewport={numItemsInViewport}
      data-last={last}
      data-first={firstState}
      aria-busy={loading ? "true" : undefined}
      onScroll={handleScroll}
    >
      {loading ? (
        <div className={cx("loader") as string}>
          <span className="u-scroller-loading-icon" />
        </div>
      ) : null}
      <div data-u-scroller-content className={cx("content") as string} style={{ height: items.length * itemSize }}>
        {contentTemplate
          ? contentTemplate({ items: visibleItems, getItemOptions, itemSize, loading: loading ?? false })
          : visibleItems.map(({ index, value }) => (
              <div
                key={index}
                data-u-scroller-item
                className={cx("item") as string}
                style={{ top: index * itemSize }}
              >
                {String(value)}
              </div>
            ))}
      </div>
    </div>
  );
});
UScroller.displayName = "UScroller";

// packages/vue/src/scroller/Scroller.vue
<template>
  <div
    ref="elementRef"
    :class="cx('root')"
    :data-num-items-in-viewport="numItemsInViewport"
    :data-last="last"
    :data-first="first"
    :aria-busy="loading ? 'true' : null"
    @scroll="onScroll"
  >
    <div v-if="loading" :class="cx('loader')">
      <span class="u-scroller-loading-icon"></span>
    </div>
    <div :class="cx('content')" data-u-scroller-content :style="{ height: items.length * itemSize + 'px' }">
      <slot name="content" :items="visibleItems" :get-item-options="getItemOptions" :item-size="itemSize" :loading="loading">
        <div
          v-for="entry in visibleItems"
          :key="entry.index"
          :class="cx('item')"
          data-u-scroller-item
          :style="{ top: entry.index * itemSize + 'px' }"
        >
          {{ entry.value }}
        </div>
      </slot>
    </div>
  </div>
</template>

<script>
import { createBaseScroller } from "./base-scroller";
import { calculateLast, calculateNumItemsInViewport } from "@ultimate/uix-data";

// Content measurement + virtual item rendering (Task 12). DEVIATION from
// the task brief's example: the brief drops `immediate: true` from the
// `items` watcher (relying solely on `mounted()`'s explicit recompute()
// call for the initial computation). That is a genuine regression, not a
// harmless redundancy — verified empirically by running Task 11's existing
// `clamps last (getLast) against the live items array length` test against
// the brief's code as-written: it failed (`data-last` read as "0" instead
// of "5") even though `this.last` was internally correct (5) by the end of
// `mounted()`. Root cause: Vue's lifecycle commits the *first* DOM patch
// before `mounted()` fires, so a `mounted()`-only recompute() reactively
// triggers a *second*, asynchronously-queued re-render — invisible to any
// assertion (like this existing, approved test) that reads the DOM
// synchronously right after `mount()` without `await nextTick()`. Keeping
// `immediate: true` fires the watcher during component creation, before
// the first render, so the first DOM patch already reflects the correct
// value. `mounted()`'s own recompute() (using the real measured
// `offsetHeight`, unavailable at `created()` time) then still runs
// immediately after, correcting `contentSize` from its `created()`-time
// value of 0 to the real measured value via a second, expected
// reactive re-render.
export default {
  name: "UScroller",
  extends: createBaseScroller(),
  props: {
    disabled: { type: Boolean, default: false },
    loading: { type: Boolean, default: false },
    lazy: { type: Boolean, default: false },
  },
  emits: ["lazy-load"],
  data() {
    return {
      first: 0,
      last: 0,
      numItemsInViewport: 0,
      contentSize: 0,
      resizeObserver: null,
    };
  },
  computed: {
    resolvedNumToleratedItems() {
      return this.numToleratedItems !== null ? this.numToleratedItems : Math.ceil(this.numItemsInViewport / 2);
    },
    visibleItems() {
      if (this.disabled) {
        return this.items.map((value, index) => ({ index, value }));
      }
      const result = [];
      for (let i = this.first; i < this.last; i++) {
        result.push({ index: i, value: this.items[i] });
      }
      return result;
    },
  },
  watch: {
    items: {
      immediate: true,
      handler() {
        this.recompute();
      },
    },
    itemSize: {
      handler() {
        this.recompute();
      },
    },
  },
  mounted() {
    // Measures the root viewport element's offsetHeight — matching real
    // PrimeVue's this.element.offsetHeight measurement exactly
    // (VirtualScroller.vue:289, pinned commit 66dde6788220fc9e6822342919d1ceb0e3460ece),
    // not clientHeight. PrimeVue's real source also genuinely uses
    // ResizeObserver here (VirtualScroller.vue:596-599), so this mirrors
    // real upstream Vue exactly, not just a modern-choice substitute the
    // way Angular's/React's ResizeObserver usage is.
    this.contentSize = this.$refs.elementRef.offsetHeight;
    this.resizeObserver = new ResizeObserver(() => {
      this.contentSize = this.$refs.elementRef.offsetHeight;
      // DEVIATION from the brief's example: the brief's ResizeObserver
      // callback only updates `contentSize`, without calling recompute().
      // `numItemsInViewport`/`last` have no separate watcher on
      // `contentSize`, so without this call they would go stale after any
      // resize past the very first one (and the two new measurement tests,
      // which re-invoke the captured `resizeObserverCallback` to simulate a
      // resize after `mount()`, would never observe the updated viewport
      // size). Calling recompute() here keeps behavior correct on every
      // subsequent resize, matching real PrimeVue's onResize() handler,
      // which recomputes on every ResizeObserver firing.
      this.recompute();
    });
    this.resizeObserver.observe(this.$refs.elementRef);
    this.recompute();
  },
  beforeUnmount() {
    this.resizeObserver?.disconnect();
  },
  methods: {
    recompute() {
      this.numItemsInViewport = calculateNumItemsInViewport(this.contentSize, this.itemSize);
      const rawLast = calculateLast(this.first, this.numItemsInViewport, this.resolvedNumToleratedItems);
      this.last = this.getLast(rawLast);
    },
    getLast(last = 0, isCols = false) {
      if (!this.items) return 0;
      const liveLength = isCols ? this.items.length : this.items.length; // isCols branch unreachable in vertical-only scope (Global Constraints)
      return Math.min(liveLength, last);
    },
    onScroll() {
      const newFirst = Math.floor(this.$refs.elementRef.scrollTop / (this.itemSize || 1));
      if (newFirst !== this.first) {
        this.first = newFirst;
        this.recompute();
        if (this.lazy) {
          const first = this.first;
          const last = this.last;
          Promise.resolve().then(() => {
            this.$emit("lazy-load", { first, last });
          });
        }
      }
    },
    scrollTo(options) {
      this.$refs.elementRef.scrollTo(options);
    },
    scrollToIndex(index, behavior = "auto") {
      this.scrollTo({ top: index * this.itemSize, behavior });
    },
    getItemOptions(index) {
      return {
        index,
        count: this.items.length,
        first: index === 0,
        last: index === this.items.length - 1,
        even: index % 2 === 0,
        odd: index % 2 !== 0,
      };
    },
  },
};
</script>
