// packages/vue/src/data-view/DataView.vue
<script>
import { createBaseDataView } from "./BaseDataView";
import Paginator from "../paginator/Paginator.vue";

function field(item, path) {
  if (typeof path !== "string" || !path) return undefined;
  return path.split(".").reduce((value, key) => (value == null ? undefined : value[key]), item);
}

function compare(a, b) {
  if (a == null && b == null) return 0;
  if (a == null) return -1;
  if (b == null) return 1;
  return typeof a === "number" && typeof b === "number"
    ? a - b
    : String(a).localeCompare(String(b));
}

function pageNumber(value) {
  return Number.isFinite(value) && value > 0 ? Math.floor(value) : 0;
}

export default {
  name: "UDataView",
  extends: createBaseDataView(),
  components: { Paginator },
  data() {
    return { pageFirst: pageNumber(this.first), pageRows: pageNumber(this.rows) };
  },
  watch: {
    first(value) {
      this.pageFirst = pageNumber(value);
    },
    rows(value) {
      this.pageRows = pageNumber(value);
    },
    pageFirst() {
      this.emitLazy();
    },
    pageRows() {
      this.emitLazy();
    },
    sortField() {
      this.emitLazy();
    },
    sortOrder() {
      this.emitLazy();
    },
    lazy() {
      this.emitLazy();
    },
  },
  mounted() {
    this.emitLazy();
  },
  computed: {
    sourceValue() {
      return Array.isArray(this.value) ? this.value : [];
    },
    layoutMode() {
      return this.layout === "grid" ? "grid" : "list";
    },
    normalizedSortOrder() {
      return this.sortOrder === -1 ? -1 : 1;
    },
    processed() {
      if (this.lazy || typeof this.sortField !== "string" || !this.sortField)
        return this.sourceValue;
      return [...this.sourceValue].sort(
        (a, b) =>
          compare(field(a, this.sortField), field(b, this.sortField)) * this.normalizedSortOrder
      );
    },
    count() {
      return this.lazy && Number.isFinite(this.totalRecords) && this.totalRecords >= 0
        ? this.totalRecords
        : this.processed.length;
    },
    pagedValue() {
      return this.lazy || !this.paginator || this.pageRows === 0
        ? this.processed
        : this.processed.slice(this.pageFirst, this.pageFirst + this.pageRows);
    },
    showPaginator() {
      return this.paginator && (this.alwaysShowPaginator || this.count > this.pageRows);
    },
    report() {
      const pages = this.pageRows > 0 ? Math.ceil(this.count / this.pageRows) : 0;
      return this.currentPageReportTemplate
        .replaceAll("{first}", String(this.count ? this.pageFirst + 1 : 0))
        .replaceAll("{last}", String(Math.min(this.pageFirst + this.pageRows, this.count)))
        .replaceAll("{totalRecords}", String(this.count))
        .replaceAll(
          "{currentPage}",
          String(pages ? Math.floor(this.pageFirst / this.pageRows) + 1 : 0)
        )
        .replaceAll("{totalPages}", String(pages))
        .replaceAll("{rows}", String(this.pageRows));
    },
  },
  methods: {
    identity(item, index) {
      if (this.dataKey) return field(item, this.dataKey);
      return typeof this.trackBy === "function" ? this.trackBy(item, index) : index;
    },
    onPage(event) {
      if (!event || !Number.isFinite(event.first) || !Number.isFinite(event.rows)) return;
      this.pageFirst = pageNumber(event.first);
      this.pageRows = pageNumber(event.rows);
      this.$emit("page", event);
      this.$emit("update:first", this.pageFirst);
      this.$emit("update:rows", this.pageRows);
    },
    changeRows(event) {
      const rows = pageNumber(Number(event?.target?.value));
      if (rows > 0)
        this.onPage({ first: 0, rows, page: 0, pageCount: Math.ceil(this.count / rows) });
    },
    emitLazy() {
      if (this.lazy)
        this.$emit("lazy-load", {
          first: this.pageFirst,
          rows: this.pageRows,
          sortField: typeof this.sortField === "string" ? this.sortField : null,
          sortOrder: this.normalizedSortOrder,
        });
    },
  },
};
</script>

<template>
  <div :class="cx('root')" :aria-busy="loading">
    <span v-if="loading" role="status" :class="loadingIcon">Loading</span>
    <Paginator
      v-if="showPaginator && paginatorPosition !== 'bottom'"
      :first="pageFirst"
      :rows="pageRows"
      :total-records="count"
      @page="onPage"
    />
    <div v-if="layoutMode === 'grid'" :class="cx('list', { layout: 'grid' })" role="list">
      <slot name="grid" :items="pagedValue">
        <div
          v-for="(item, index) in pagedValue"
          :key="identity(item, index)"
          :class="cx('listItem')"
          role="listitem"
        >
          {{ typeof itemTemplate === "function" ? itemTemplate(item, "grid") : String(item) }}
        </div>
      </slot>
    </div>
    <div v-else :class="cx('list', { layout: 'list' })" role="list">
      <slot name="list" :items="pagedValue">
        <div
          v-for="(item, index) in pagedValue"
          :key="identity(item, index)"
          :class="cx('listItem')"
          role="listitem"
        >
          {{ typeof itemTemplate === "function" ? itemTemplate(item, "list") : String(item) }}
        </div>
      </slot>
    </div>
    <div v-if="!pagedValue.length">{{ emptyMessage }}</div>
    <Paginator
      v-if="showPaginator && paginatorPosition !== 'top'"
      :first="pageFirst"
      :rows="pageRows"
      :total-records="count"
      @page="onPage"
    />
    <template v-if="paginator">
      <label v-if="rowsPerPageOptions.length"
        >Rows per page<select :value="pageRows" @change="changeRows">
          <option v-for="size in rowsPerPageOptions" :key="size" :value="size">{{ size }}</option>
        </select></label
      >
      <span aria-live="polite">{{ report }}</span>
    </template>
  </div>
</template>

// packages/react/src/data-view/data-view.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { UPaginator, type PaginatorPageChangeEvent } from "../paginator/paginator";
import { dataViewStyleModule } from "./data-view-style";

function field(item: unknown, path: string): unknown {
  return path
    .split(".")
    .reduce<unknown>(
      (value, key) =>
        value != null && typeof value === "object"
          ? (value as Record<string, unknown>)[key]
          : undefined,
      item
    );
}

function compare(a: unknown, b: unknown): number {
  if (a == null && b == null) return 0;
  if (a == null) return -1;
  if (b == null) return 1;
  return typeof a === "number" && typeof b === "number"
    ? a - b
    : String(a).localeCompare(String(b));
}

export interface UDataViewProps<T = unknown> {
  value: T[];
  itemTemplate: (item: T, layout: "list" | "grid") => React.ReactNode;
  layout?: "list" | "grid";
  paginator?: boolean;
  first?: number;
  rows?: number;
  totalRecords?: number;
  rowsPerPageOptions?: number[];
  paginatorPosition?: "top" | "bottom" | "both";
  alwaysShowPaginator?: boolean;
  currentPageReportTemplate?: string;
  sortField?: string;
  sortOrder?: 1 | -1;
  lazy?: boolean;
  loading?: boolean;
  loadingIcon?: React.ReactNode;
  emptyMessage?: string;
  dataKey?: string;
  trackBy?: (item: T, index: number) => React.Key;
  onPageChange?: (event: PaginatorPageChangeEvent) => void;
  onLazyLoad?: (event: {
    first: number;
    rows: number;
    sortField?: string;
    sortOrder: 1 | -1;
  }) => void;
  className?: string;
}

export function UDataView<T = unknown>({
  value,
  itemTemplate,
  layout = "list",
  paginator = false,
  first = 0,
  rows = 0,
  totalRecords,
  rowsPerPageOptions = [],
  paginatorPosition = "bottom",
  alwaysShowPaginator = true,
  currentPageReportTemplate = "{first} to {last} of {totalRecords}",
  sortField,
  sortOrder = 1,
  lazy = false,
  loading = false,
  loadingIcon = "Loading",
  emptyMessage = "No results found",
  dataKey,
  trackBy,
  onPageChange,
  onLazyLoad,
  className,
}: UDataViewProps<T>): React.ReactElement {
  const { cx } = useComponentBase({ componentName: "data-view", styleModule: dataViewStyleModule });
  const [pageFirst, setPageFirst] = React.useState(first);
  const [pageRows, setPageRows] = React.useState(rows);

  React.useEffect(() => {
    setPageFirst(first);
  }, [first]);

  React.useEffect(() => {
    setPageRows(rows);
  }, [rows]);

  React.useEffect(() => {
    if (lazy) onLazyLoad?.({ first: pageFirst, rows: pageRows, sortField, sortOrder });
  }, [lazy, pageFirst, pageRows, sortField, sortOrder, onLazyLoad]);

  const processed = React.useMemo(() => {
    if (lazy || !sortField) return value;
    return [...value].sort((a, b) => compare(field(a, sortField), field(b, sortField)) * sortOrder);
  }, [value, lazy, sortField, sortOrder]);
  const count = lazy ? (totalRecords ?? value.length) : processed.length;
  const paged =
    lazy || !paginator || pageRows <= 0
      ? processed
      : processed.slice(pageFirst, pageFirst + pageRows);
  const changePage = (event: PaginatorPageChangeEvent): void => {
    setPageFirst(event.first);
    setPageRows(event.rows);
    onPageChange?.(event);
  };
  const pageCount = pageRows > 0 ? Math.ceil(count / pageRows) : 0;
  const report = currentPageReportTemplate
    .replaceAll("{first}", String(count ? pageFirst + 1 : 0))
    .replaceAll("{last}", String(Math.min(pageFirst + pageRows, count)))
    .replaceAll("{totalRecords}", String(count))
    .replaceAll("{currentPage}", String(pageCount ? Math.floor(pageFirst / pageRows) + 1 : 0))
    .replaceAll("{totalPages}", String(pageCount))
    .replaceAll("{rows}", String(pageRows));
  const showPaginator = paginator && (alwaysShowPaginator || count > pageRows);
  const paging = (
    <UPaginator first={pageFirst} rows={pageRows} totalRecords={count} onPageChange={changePage} />
  );
  const key = (item: T, index: number): React.Key =>
    dataKey ? String(field(item, dataKey)) : trackBy ? trackBy(item, index) : index;

  return (
    <div className={[cx("root"), className].filter(Boolean).join(" ")} aria-busy={loading}>
      {loading && <span role="status">{loadingIcon}</span>}
      {showPaginator && paginatorPosition !== "bottom" && paging}
      {layout === "grid" ? (
        <div className={cx("list", { layout: "grid" })} role="list">
          {paged.length ? (
            paged.map((item, index) => (
              <div className={cx("listItem")} role="listitem" key={key(item, index)}>
                {itemTemplate(item, "grid")}
              </div>
            ))
          ) : (
            <div>{emptyMessage}</div>
          )}
        </div>
      ) : (
        <ul className={cx("list", { layout: "list" })}>
          {paged.length ? (
            paged.map((item, index) => (
              <li className={cx("listItem")} key={key(item, index)}>
                {itemTemplate(item, "list")}
              </li>
            ))
          ) : (
            <li>{emptyMessage}</li>
          )}
        </ul>
      )}
      {showPaginator && paginatorPosition !== "top" && paging}
      {paginator && (
        <>
          {rowsPerPageOptions.length > 0 && (
            <label>
              Rows per page
              <select
                value={pageRows}
                onChange={(event) => {
                  const nextRows = Number(event.target.value);
                  if (nextRows > 0)
                    changePage({
                      first: 0,
                      rows: nextRows,
                      page: 0,
                      pageCount: Math.ceil(count / nextRows),
                    });
                }}
              >
                {rowsPerPageOptions.map((size) => (
                  <option key={size} value={size}>
                    {size}
                  </option>
                ))}
              </select>
            </label>
          )}
          <span aria-live="polite">{report}</span>
        </>
      )}
    </div>
  );
}
