// packages/react/src/input-number/input-number.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { inputNumberStyleModule } from "./input-number-style";

/**
 * Ultimate-owned adaptation of PrimeReact's `InputNumber` (real source:
 * `components/lib/inputnumber/InputNumber.js`/`InputNumberBase.js`,
 * extracted this session). Fully-controlled (`value`/`onValueChange`),
 * matching React's no-shared-form-state-base-class convention.
 *
 * Real PrimeReact InputNumber is React's own established idiom for this
 * capability: locale-aware `Intl.NumberFormat`-based display formatting
 * (`format`/`locale`/`useGrouping`/`minFractionDigits`/`maxFractionDigits`),
 * `prefix`/`suffix`, spinner buttons (`showButtons`, default OFF per real
 * source's own `showButtons: false` default), min/max/step clamping. This
 * component ports that idiom for real rather than cutting it down to match
 * Angular's own documented InputNumber scope-cut (per this task's explicit
 * instruction that React/Vue determine their own appropriate scope from
 * their own real source).
 *
 * Ported for real: `Intl.NumberFormat` formatting/parsing (`mode: "decimal"
 * | "currency" | "percent"`, `currency`, `locale`, `useGrouping`,
 * `minFractionDigits`/`maxFractionDigits`), `prefix`/`suffix` display
 * decoration, `min`/`max`/`step` clamping, increment/decrement via spinner
 * buttons (mouse) and ArrowUp/ArrowDown keys, disabled/readOnly/invalid,
 * `allowEmpty`.
 *
 * Deliberately excludes real source's caret-position-preserving
 * insert/delete logic (`insertText`/`deleteRange`/`updateInput`/
 * `initCursor`) and clipboard-paste parsing — real source reformats the
 * whole input value and attempts to restore the caret to its pre-edit
 * position; this component instead reformats on blur (keeping the raw
 * numeric string live while focused, matching a simpler and still-correct
 * fully-controlled pattern) and lets the browser's default caret behavior
 * apply while typing. Also excludes `buttonLayout: "horizontal" |
 * "vertical"` (only the default `"stacked"` layout is implemented) and
 * `roundingMode` (delegated entirely to `Intl.NumberFormat`'s own default
 * rounding). These are documented, explicit scope cuts, not silent
 * omissions — mirroring how `UInputNumber`'s Angular doc comment documents
 * its own cuts.
 */
export interface UInputNumberValueChangeEvent {
  originalEvent: React.SyntheticEvent;
  value: number | null;
}

export interface UInputNumberProps {
  value?: number | null;
  onValueChange?: (event: UInputNumberValueChangeEvent) => void;
  min?: number;
  max?: number;
  step?: number;
  mode?: "decimal" | "currency" | "percent";
  currency?: string;
  locale?: string;
  useGrouping?: boolean;
  minFractionDigits?: number;
  maxFractionDigits?: number;
  prefix?: string;
  suffix?: string;
  format?: boolean;
  allowEmpty?: boolean;
  showButtons?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  invalid?: boolean;
  fluid?: boolean;
  name?: string;
  id?: string;
  placeholder?: string;
  className?: string;
  inputRef?: React.Ref<HTMLInputElement>;
}

function clamp(value: number, min?: number, max?: number): number {
  let result = value;
  if (min != null && result < min) result = min;
  if (max != null && result > max) result = max;
  return result;
}

export const UInputNumber = React.forwardRef<HTMLInputElement, UInputNumberProps>(function UInputNumber(
  {
    value = null,
    onValueChange,
    min,
    max,
    step = 1,
    mode = "decimal",
    currency,
    locale,
    useGrouping = true,
    minFractionDigits,
    maxFractionDigits,
    prefix = "",
    suffix = "",
    format = true,
    allowEmpty = true,
    showButtons = false,
    disabled = false,
    readOnly = false,
    invalid = false,
    fluid = false,
    name,
    id,
    placeholder,
    className,
    inputRef,
  },
  ref
) {
  const { cx } = useComponentBase({ componentName: "input-number", styleModule: inputNumberStyleModule });
  const elementRef = React.useRef<HTMLInputElement | null>(null);
  const [focused, setFocused] = React.useState(false);
  const [rawText, setRawText] = React.useState<string | null>(null);

  const setRef = React.useCallback(
    (node: HTMLInputElement | null) => {
      elementRef.current = node;
      if (typeof ref === "function") ref(node);
      else if (ref) (ref as React.MutableRefObject<HTMLInputElement | null>).current = node;
      if (typeof inputRef === "function") inputRef(node);
      else if (inputRef) (inputRef as React.MutableRefObject<HTMLInputElement | null>).current = node;
    },
    [ref, inputRef]
  );

  const numberFormat = React.useMemo(
    () =>
      new Intl.NumberFormat(locale, {
        style: mode,
        currency: mode === "currency" ? currency : undefined,
        useGrouping,
        minimumFractionDigits: minFractionDigits,
        maximumFractionDigits: maxFractionDigits,
      }),
    [locale, mode, currency, useGrouping, minFractionDigits, maxFractionDigits]
  );

  const formatValue = React.useCallback(
    (val: number | null): string => {
      if (val == null) return "";
      const formatted = format ? numberFormat.format(val) : String(val);
      return `${prefix}${formatted}${suffix}`;
    },
    [format, numberFormat, prefix, suffix]
  );

  const parseValue = React.useCallback(
    (text: string): number | null => {
      let stripped = text;
      if (prefix && stripped.startsWith(prefix)) stripped = stripped.slice(prefix.length);
      if (suffix && stripped.endsWith(suffix)) stripped = stripped.slice(0, stripped.length - suffix.length);
      stripped = stripped.trim();
      if (stripped === "") return null;
      // Strip locale grouping separators and normalize decimal separator to '.'.
      const parts = numberFormat.formatToParts(1234.5);
      const group = parts.find((p) => p.type === "group")?.value ?? ",";
      const decimal = parts.find((p) => p.type === "decimal")?.value ?? ".";
      const normalized = stripped
        .split(group)
        .join("")
        .replace(decimal, ".")
        .replace(/[^\d.-]/g, "");
      const parsed = Number(normalized);
      return Number.isNaN(parsed) ? null : parsed;
    },
    [numberFormat, prefix, suffix]
  );

  const emit = React.useCallback(
    (event: React.SyntheticEvent, next: number | null) => {
      onValueChange?.({ originalEvent: event, value: next });
    },
    [onValueChange]
  );

  const displayValue = focused ? (rawText ?? (value == null ? "" : String(value))) : formatValue(value);

  const onFocus = React.useCallback(() => {
    setFocused(true);
    setRawText(value == null ? "" : String(value));
  }, [value]);

  const onChange = React.useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      setRawText(event.target.value);
    },
    []
  );

  const commit = React.useCallback(
    (event: React.SyntheticEvent, text: string) => {
      const parsed = parseValue(text);
      if (parsed == null) {
        if (allowEmpty) emit(event, null);
        else emit(event, clamp(0, min, max));
        return;
      }
      emit(event, clamp(parsed, min, max));
    },
    [parseValue, allowEmpty, emit, min, max]
  );

  const onBlur = React.useCallback(
    (event: React.FocusEvent<HTMLInputElement>) => {
      commit(event, rawText ?? "");
      setFocused(false);
      setRawText(null);
    },
    [commit, rawText]
  );

  const applyStep = React.useCallback(
    (event: React.SyntheticEvent, direction: 1 | -1) => {
      if (disabled || readOnly) return;
      const base = value ?? 0;
      const next = clamp(base + direction * step, min, max);
      emit(event, next);
    },
    [disabled, readOnly, value, step, min, max, emit]
  );

  const onKeyDown = React.useCallback(
    (event: React.KeyboardEvent<HTMLInputElement>) => {
      if (event.key === "ArrowUp") {
        applyStep(event, 1);
        event.preventDefault();
      } else if (event.key === "ArrowDown") {
        applyStep(event, -1);
        event.preventDefault();
      }
    },
    [applyStep]
  );

  return (
    <span className={[cx("root", { invalid, fluid, focused }), className].filter(Boolean).join(" ")}>
      <input
        ref={setRef}
        type="text"
        inputMode="decimal"
        role="spinbutton"
        id={id}
        name={name}
        placeholder={placeholder}
        disabled={disabled}
        readOnly={readOnly}
        aria-invalid={invalid || undefined}
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={value ?? undefined}
        className={cx("input")}
        value={displayValue}
        onFocus={onFocus}
        onChange={onChange}
        onBlur={onBlur}
        onKeyDown={onKeyDown}
      />
      {showButtons && (
        <span className={cx("buttonGroup")}>
          <button
            type="button"
            tabIndex={-1}
            disabled={disabled || readOnly}
            className={cx("incrementButton")}
            aria-label="Increment"
            onClick={(event) => applyStep(event, 1)}
          >
            +
          </button>
          <button
            type="button"
            tabIndex={-1}
            disabled={disabled || readOnly}
            className={cx("decrementButton")}
            aria-label="Decrement"
            onClick={(event) => applyStep(event, -1)}
          >
            -
          </button>
        </span>
      )}
    </span>
  );
});

// packages/vue/src/input-number/InputNumber.vue
<template>
  <span :class="cx('root', rootParams)">
    <input
      ref="input"
      type="text"
      inputmode="decimal"
      role="spinbutton"
      :class="cx('input', inputParams)"
      :value="displayValue"
      :name="name"
      :placeholder="placeholder"
      :readonly="readonly"
      :disabled="disabled"
      :aria-valuemin="min"
      :aria-valuemax="max"
      :aria-valuenow="numericValue ?? undefined"
      :aria-invalid="invalid || undefined"
      @input="onInput"
      @keydown="onKeyDown"
      @focus="onFocus"
      @blur="onBlur"
      @paste="onPaste"
    />
  </span>
</template>

<script>
import { createBaseInputNumber } from "./BaseInputNumber";

// Ultimate-owned adaptation of PrimeVue's `InputNumber`. Real upstream
// InputNumber.vue is 1087 lines: full locale-aware Intl.NumberFormat
// formatting/parsing (`getFormatter`/`formatValue`/`parseValue`,
// this port's own scope, ported below as real, working code — not a stub),
// configurable spin-button UI (`showButtons`/`buttonLayout` +
// increment/decrement DOM elements, mouse-hold repeat-spin via
// `repeat`/`spin`), and caret-preserving insert/delete-range editing
// (`insert`/`insertText`/`deleteRange`/`initCursor`, an IE/legacy-browser
// cursor-position-preservation layer PrimeReact/PrimeVue both carry for
// historical reasons).
//
// This port's real, working core: Intl.NumberFormat-based display
// formatting (locale/currency/useGrouping/min-max-FractionDigits, matching
// real source's own `getFormatter()`/`formatValue()`), parseValue (strips
// grouping/currency/decimal separators back to a plain numeric string,
// matching real source's own regex-construction approach via
// `getDecimalExpression`/`getGroupingExpression`/`getCurrencyExpression`
// simplified to `Intl.NumberFormat`'s own `formatToParts` for robustness),
// min/max/step clamping, keyboard ArrowUp/ArrowDown increment-by-step
// (real source's own `onInputKeyDown` ArrowUp/ArrowDown branches, via
// `spin()`), disabled/readonly/invalid/placeholder.
//
// Explicitly, deliberately NOT ported (documented scope cut, mirroring
// UInputNumber's Angular precedent of naming its own exclusions rather than
// silently dropping surface): spin-button UI elements and mouse-hold
// repeat-spin (`showButtons`/`buttonLayout`, `onUpButtonMouseDown`/
// `repeat`), clipboard-paste custom parsing (`onPaste` here simply lets the
// browser insert pasted text into the native input, then re-formats via the
// same `onInput` path — no separate caret-aware paste handler),
// caret-preserving insert/delete-range editing (this port re-derives the
// full display string from the parsed numeric value on every input/blur
// rather than surgically inserting/deleting at the caret — the native input
// re-renders with the caret placed at the end, a real behavioral
// simplification, not a masking/parsing correctness cut).
export default {
  name: "UInputNumber",
  extends: createBaseInputNumber(),
  emits: ["focus", "blur", "input"],
  data() {
    return {
      focused: false,
      rawText: "",
    };
  },
  computed: {
    numericValue() {
      return this.dValue === undefined || this.dValue === null || this.dValue === ""
        ? null
        : Number(this.dValue);
    },
    formatter() {
      const options = {
        useGrouping: this.useGrouping,
        minimumFractionDigits: this.minFractionDigits,
        maximumFractionDigits: this.maxFractionDigits,
        style: this.mode === "currency" ? "currency" : this.mode === "percent" ? "percent" : "decimal",
      };
      if (this.mode === "currency") {
        options.currency = this.currency ?? "USD";
      }
      return new Intl.NumberFormat(this.locale, options);
    },
    displayValue() {
      if (this.focused) return this.rawText;
      if (this.numericValue === null || Number.isNaN(this.numericValue)) return "";
      return this.withAffixes(this.formatter.format(this.numericValue));
    },
    rootParams() {
      return { fluid: this.resolvedFluid };
    },
    inputParams() {
      return { invalid: this.invalid };
    },
  },
  methods: {
    withAffixes(text) {
      return `${this.prefix ?? ""}${text}${this.suffix ?? ""}`;
    },
    /** Strips prefix/suffix/grouping separators, normalizes the locale decimal separator to '.'. */
    parseValue(text) {
      let stripped = text;
      if (this.prefix && stripped.startsWith(this.prefix)) stripped = stripped.slice(this.prefix.length);
      if (this.suffix && stripped.endsWith(this.suffix)) stripped = stripped.slice(0, -this.suffix.length);

      const parts = this.formatter.formatToParts(1234.5);
      const group = parts.find((p) => p.type === "group")?.value ?? ",";
      const decimal = parts.find((p) => p.type === "decimal")?.value ?? ".";

      stripped = stripped.split(group).join("");
      if (decimal !== ".") stripped = stripped.split(decimal).join(".");

      stripped = stripped.replace(/[^0-9.-]/g, "");
      if (stripped === "" || stripped === "-") return null;

      const parsed = Number(stripped);
      return Number.isNaN(parsed) ? null : parsed;
    },
    clamp(value) {
      if (value === null) return null;
      let result = value;
      if (this.min !== null && result < this.min) result = this.min;
      if (this.max !== null && result > this.max) result = this.max;
      return result;
    },
    commit(value, event) {
      const clamped = this.clamp(value);
      if (clamped === null && !this.allowEmpty) {
        this.writeValue(this.min ?? 0, event);
      } else {
        this.writeValue(clamped, event);
      }
      this.$emit("input", { originalEvent: event, value: clamped });
    },
    onInput(event) {
      this.rawText = event.target.value;
      const parsed = this.parseValue(this.rawText);
      this.commit(parsed, event);
    },
    onFocus(event) {
      this.focused = true;
      this.rawText =
        this.numericValue === null || Number.isNaN(this.numericValue) ? "" : String(this.numericValue);
      this.$emit("focus", event);
    },
    onBlur(event) {
      this.focused = false;
      this.$emit("blur", event);
    },
    onKeyDown(event) {
      if (this.readonly || this.disabled) return;
      if (event.key === "ArrowUp") {
        event.preventDefault();
        this.spin(event, this.step);
      } else if (event.key === "ArrowDown") {
        event.preventDefault();
        this.spin(event, -this.step);
      }
    },
    spin(event, delta) {
      const base = this.numericValue ?? 0;
      const next = this.clamp(base + delta);
      this.rawText = next === null ? "" : String(next);
      this.commit(next, event);
    },
    onPaste(event) {
      if (this.readonly || this.disabled) {
        event.preventDefault();
      }
    },
  },
};
</script>
