// packages/react/src/tiered-menu/tiered-menu.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { UTieredMenuSub } from "./tiered-menu-sub";
import { tieredMenuStyleModule } from "./tiered-menu-style";
import type { UMenuItem } from "../menu";

export interface UTieredMenuProps {
  /** An array of menuitems. */
  model?: UMenuItem[];
  /** Defines if menu would displayed as a popup. */
  popup?: boolean;
  /** Fired when an item is selected. */
  onItemSelect?: (event: { originalEvent: React.SyntheticEvent; item: UMenuItem }) => void;
  /** Callback to invoke when the popup menu is shown. */
  onShow?: () => void;
  /** Callback to invoke when the popup menu is hidden. */
  onHide?: () => void;
  className?: string;
}

export interface UTieredMenuHandle {
  toggle: () => void;
  show: () => void;
  hide: () => void;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `TieredMenu` component (see
 * `.vendor-extracted/react/tieredmenu/TieredMenu.js`; `TieredMenuSub`
 * split into `UTieredMenuSub`). Renders nested popup submenus via a
 * recursive sub-component, either inline (`popup: false`, matching
 * `UMenu`'s own inline mode) or as a toggleable popup (`popup: true`).
 *
 * Real PrimeReact's `TieredMenu` (no import of `../menu`) is a standalone,
 * independent component — it does NOT compose `Menu`.
 */
export const UTieredMenu = React.forwardRef<UTieredMenuHandle, UTieredMenuProps>(function UTieredMenu(
  { model = [], popup = false, onItemSelect, onShow, onHide, className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "tiered-menu", styleModule: tieredMenuStyleModule });
  const [visible, setVisible] = React.useState(!popup);

  const hide = React.useCallback(() => {
    setVisible((current) => {
      if (!current) return current;
      onHide?.();
      return false;
    });
  }, [onHide]);

  const show = React.useCallback(() => {
    setVisible((current) => {
      if (current) return current;
      onShow?.();
      return true;
    });
  }, [onShow]);

  React.useImperativeHandle(
    ref,
    () => ({
      toggle: () => (visible ? hide() : show()),
      show,
      hide,
    }),
    [visible, show, hide]
  );

  React.useEffect(() => {
    if (!popup || !visible) return;
    const onEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") hide();
    };
    document.addEventListener("keydown", onEscape);
    return () => document.removeEventListener("keydown", onEscape);
  }, [popup, visible, hide]);

  const handleItemSelect = (event: { originalEvent: React.SyntheticEvent; item: UMenuItem }) => {
    onItemSelect?.(event);
    if (popup) hide();
  };

  if (popup && !visible) return null;

  return (
    <div className={[cx("root", { popup }), className].filter(Boolean).join(" ")}>
      <UTieredMenuSub items={model} root cx={cx} onItemSelect={handleItemSelect} />
    </div>
  );
});

// packages/vue/src/tiered-menu/TieredMenu.vue
<template>
  <div v-if="popup ? visible : true" :class="cx('root', { popup })">
    <UTieredMenuSub :items="model" :root="true" @item-select="handleItemSelect" />
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `TieredMenu` component (see
// `.vendor-extracted/vue/tieredmenu/TieredMenu.vue`, `TieredMenuSub.vue`).
// Renders nested popup submenus via a recursive sub-component, either
// inline (`popup: false`, matching `UMenu`'s own inline mode) or as a
// toggleable popup (`popup: true`).
//
// Real PrimeVue's `TieredMenu` (`extends BaseComponent`, no import of
// `primevue/menu`) is a standalone, independent component — it does NOT
// compose or wrap `Menu`. This adaptation follows that same independent
// shape. Real upstream wraps its root in `<Portal :appendTo :disabled=
// "!popup">` (verified this task's Step 1) — this adaptation deliberately
// does NOT use `Portal`/`Teleport` here, matching the binding choice
// already made by this same capability's Angular/React `UTieredMenu`
// siblings (a plain `v-if`-toggled wrapper, in-place, CSS-positioned via
// `.u-tieredmenu-overlay`) — cross-framework consistency for this
// capability takes precedence over an exact 1:1 port of upstream's own
// Portal usage, since neither of this task's other two realizations uses
// one either.
import { createBaseTieredMenu } from "./BaseTieredMenu";
import TieredMenuSub from "./TieredMenuSub.vue";

export default {
  name: "UTieredMenu",
  extends: createBaseTieredMenu(),
  inheritAttrs: false,
  emits: ["item-select", "show", "hide"],
  components: { UTieredMenuSub: TieredMenuSub },
  data() {
    return {
      visible: false,
    };
  },
  escapeListener: null,
  beforeUnmount() {
    this.unbindEscapeListener();
  },
  methods: {
    handleItemSelect(event) {
      this.$emit("item-select", event);
      if (this.popup) {
        this.hide();
      }
    },
    toggle() {
      this.visible ? this.hide() : this.show();
    },
    show() {
      if (this.visible) return;
      this.visible = true;
      this.$emit("show");
      if (this.popup) this.bindEscapeListener();
    },
    hide() {
      if (!this.visible) return;
      this.visible = false;
      this.$emit("hide");
      this.unbindEscapeListener();
    },
    bindEscapeListener() {
      if (this.escapeListener) return;
      this.escapeListener = (event) => {
        if (event.key === "Escape" && this.popup && this.visible) this.hide();
      };
      document.addEventListener("keydown", this.escapeListener);
    },
    unbindEscapeListener() {
      if (!this.escapeListener) return;
      document.removeEventListener("keydown", this.escapeListener);
      this.escapeListener = null;
    },
  },
};
</script>
