// packages/vue/src/fieldset/Fieldset.vue
<template>
  <fieldset :class="cx('root', { toggleable })">
    <legend :class="cx('legend')">
      <button
        v-if="toggleable"
        :id="headerId"
        type="button"
        :aria-controls="contentId"
        :aria-expanded="!d_collapsed"
        :class="cx('toggleButton')"
        @click="toggle"
        @keydown="onKeyDown"
      >
        <span :class="cx('toggleIcon')" aria-hidden="true">{{ d_collapsed ? "+" : "−" }}</span>
        <span :class="cx('legendLabel')">{{ legend }}</span>
      </button>
      <span v-else :class="cx('legendLabel')">{{ legend }}</span>
    </legend>
    <div
      v-if="!toggleable || !d_collapsed"
      :class="cx('contentContainer')"
      role="region"
      :id="contentId"
      :aria-labelledby="headerId"
    >
      <div :class="cx('content')">
        <slot></slot>
      </div>
    </div>
  </fieldset>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Fieldset` component (see
// .vendor-extracted/vue/fieldset/Fieldset.vue). A grouping component with
// an optional `legend` heading and an optional content-toggle feature —
// matching real source's own `legend`/`toggleable`/`collapsed`/
// `update:collapsed`/`toggle` structural shape and its internal
// `d_collapsed` state pattern exactly.
//
// Deliberately excludes real source's `<transition name="p-collapsible">`
// collapse animation, its `v-ripple` directive on the toggle button, and
// its `legend`/`toggleicon` slot-override system — this port toggles
// visibility via a plain `v-if`, no enter/leave animation, same "smaller
// surface than upstream" precedent as every sibling component. Real
// source's expand/collapse glyphs (`PlusIcon`/`MinusIcon`) are not used
// here for cross-framework consistency with Angular/React (neither has a
// Plus icon yet) — plain `+`/`−` text glyphs are used instead, disclosed
// here rather than silently substituted.
import { createBaseFieldset } from "./BaseFieldset";

let uid = 0;

export default {
  name: "UFieldset",
  extends: createBaseFieldset(),
  inheritAttrs: false,
  emits: ["update:collapsed", "toggle"],
  data() {
    return {
      d_collapsed: this.collapsed,
      instanceId: `u_fieldset_${++uid}`,
    };
  },
  computed: {
    headerId() {
      return `${this.instanceId}_header`;
    },
    contentId() {
      return `${this.instanceId}_content`;
    },
  },
  watch: {
    collapsed(newValue) {
      this.d_collapsed = newValue;
    },
  },
  methods: {
    toggle(event) {
      if (!this.toggleable) return;
      this.d_collapsed = !this.d_collapsed;
      this.$emit("update:collapsed", this.d_collapsed);
      this.$emit("toggle", { originalEvent: event, value: this.d_collapsed });
      event.preventDefault();
    },
    onKeyDown(event) {
      if (event.code === "Enter" || event.code === "NumpadEnter" || event.code === "Space") {
        this.toggle(event);
      }
    },
  },
};
</script>

// packages/react/src/fieldset/fieldset.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { fieldsetStyleModule } from "./fieldset-style";

export interface UFieldsetProps {
  legend?: React.ReactNode;
  toggleable?: boolean;
  collapsed?: boolean;
  onToggle?: (event: { originalEvent: React.SyntheticEvent; value: boolean }) => void;
  children?: React.ReactNode;
  className?: string;
}

let uid = 0;

/**
 * Ultimate-owned adaptation of PrimeReact's `Fieldset` component (real
 * source: `components/lib/fieldset/Fieldset.js`). A grouping component
 * with an optional `legend` heading and an optional content-toggle
 * feature — matching real source's own `legend`/`toggleable`/`collapsed`/
 * `onToggle` structural shape (uncontrolled by default, controlled when
 * `onToggle` is supplied, exactly matching real source's own
 * `props.onToggle ? props.collapsed : collapsedState` branch).
 *
 * Deliberately excludes real source's `CSSTransition`-driven collapse
 * animation and its `Ripple` directive on the toggle button — this port
 * toggles visibility via a plain conditional render, no enter/leave
 * animation. Real source's expand/collapse glyphs (`PlusIcon`/`MinusIcon`)
 * have no `@ultimate/react-core` equivalent yet (Vue's own icon set has a
 * `MinusIcon` but no `PlusIcon` — using it here would create an
 * inconsistent per-framework glyph choice) — plain `+`/`−` text glyphs are
 * used instead in all 3 frameworks, disclosed here rather than silently
 * substituted.
 */
export const UFieldset = React.forwardRef<HTMLFieldSetElement, UFieldsetProps>(function UFieldset(
  { legend, toggleable = false, collapsed: collapsedProp = false, onToggle, children, className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "fieldset", styleModule: fieldsetStyleModule });
  const [collapsedState, setCollapsedState] = React.useState(collapsedProp);
  const collapsed = toggleable ? (onToggle ? collapsedProp : collapsedState) : false;
  const idRef = React.useRef<string>();
  if (!idRef.current) {
    idRef.current = `u_fieldset_${++uid}`;
  }
  const headerId = `${idRef.current}_header`;
  const contentId = `${idRef.current}_content`;

  const toggle = (event: React.SyntheticEvent) => {
    if (!toggleable) return;
    const next = !collapsed;
    if (!onToggle) {
      setCollapsedState(next);
    }
    onToggle?.({ originalEvent: event, value: next });
    event.preventDefault();
  };

  const onKeyDown = (event: React.KeyboardEvent) => {
    if (event.code === "Enter" || event.code === "NumpadEnter" || event.code === "Space") {
      toggle(event);
    }
  };

  return (
    <fieldset ref={ref} className={[cx("root", { toggleable }), className].filter(Boolean).join(" ")}>
      <legend className={cx("legend")}>
        {toggleable ? (
          <button
            type="button"
            id={headerId}
            aria-controls={contentId}
            aria-expanded={!collapsed}
            className={cx("toggleButton")}
            onClick={toggle}
            onKeyDown={onKeyDown}
          >
            <span className={cx("toggleIcon")} aria-hidden="true">
              {collapsed ? "+" : "−"}
            </span>
            <span className={cx("legendLabel")}>{legend}</span>
          </button>
        ) : (
          <span className={cx("legendLabel")}>{legend}</span>
        )}
      </legend>
      {(!toggleable || !collapsed) && (
        <div
          className={cx("contentContainer")}
          role="region"
          id={contentId}
          aria-labelledby={headerId}
        >
          <div className={cx("content")}>{children}</div>
        </div>
      )}
    </fieldset>
  );
});
