// packages/vue/src/toast/Toast.vue
<template>
  <div :class="cx('root', { position })">
    <div
      v-for="message of messages"
      :key="message.id"
      :class="cx('message', { severity: message.severity })"
      role="alert"
      aria-live="assertive"
      aria-atomic="true"
    >
      <div :class="cx('messageContent')">
        <div v-if="message.summary" :class="cx('summary')">{{ message.summary }}</div>
        <div v-if="message.detail" :class="cx('detail')">{{ message.detail }}</div>
      </div>
      <button
        v-if="message.closable !== false"
        type="button"
        :class="cx('closeButton')"
        aria-label="Close"
        @click="remove(message.id)"
      >
        &times;
      </button>
    </div>
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Toast` component (see
// .vendor-extracted/vue/toast/Toast.vue). Confirmed against real source:
// extends the bare `BaseComponent` tier (no v-model/writeValue) — a
// service-driven, transient-notification-stack overlay (spec §3.0's own
// description). Subscribes directly to `toastEventBus` (the already-built
// `UToastService`'s own dispatch mechanism, Task Group A,
// `@ultimate/vue-core`) for "add"/"remove"/"remove-all" events, filtering
// "add" on `group`, matching real PrimeVue's own `ToastEventBus`-listening
// mechanism exactly (`Toast.vue`'s own `mounted()`
// `ToastEventBus.on('add', this.onAdd)` etc., this port's own
// `toastEventBus` is the same event-bus primitive already wired for this
// exact purpose by Task Group A's `UToastService`).
//
// Each queued message gets its own auto-dismiss timer (`life`, default
// 3000ms, `sticky` disables it) — real source delegates this to a nested
// `ToastMessage` sub-component; this port folds that responsibility into
// `UToast` itself, same "smaller surface than upstream" precedent as
// `UMessage`'s own plain-state-gated rendering (no enter/leave
// `<transition-group>` animation, real source's own excluded).
//
// Known-pitfall discipline (per this task's own brief, both directly
// relevant to Toast): (1) `messages` is internal `data()` state driven by
// an event-bus subscription, not a prop — dismissal identity therefore
// uses each message's own stable numeric `id` (assigned once, on arrival),
// never object-reference/Proxy-identity comparison, since Vue wraps every
// prop-received object in a fresh reactive Proxy per access (this
// component's own messages are never received as a prop in the first
// place, so this is a pre-emptive precedent match, not a bug being worked
// around); (2) no Portal/Teleport composition here (unlike
// ConfirmDialog/Popover/Drawer) — Toast renders directly in-place, fixed-
// positioned via CSS, matching real PrimeVue's own Toast.vue (which itself
// composes `Portal`, but this port's own established Popover/Drawer
// precedent for "smaller surface than upstream" already covers dropping
// Portal composition where a fixed-position overlay doesn't require DOM
// relocation for stacking-context correctness — z-index alone suffices
// here, same reasoning as `UConfirmDialog`'s Vue realization).
import { toastEventBus } from "@ultimate/vue-core";
import { createBaseToast } from "./BaseToast";

let nextId = 0;

export default {
  name: "UToast",
  extends: createBaseToast(),
  inheritAttrs: false,
  data() {
    return {
      messages: [],
    };
  },
  created() {
    // Plain non-reactive instance state, deliberately not part of data()'s
    // reactive tracking (matching UPopover/UDrawer's own established
    // pattern of non-reactive instance fields for imperative bookkeeping) —
    // assigned per-instance in created(), not as a shared top-level object
    // literal (which Vue would otherwise treat as under-specified: a plain
    // object at the component-options top level is never auto-installed as
    // an instance property the way data()'s return value is).
    this.timers = {};
  },
  mounted() {
    toastEventBus.on("add", this.onAdd);
    toastEventBus.on("remove", this.onRemove);
    toastEventBus.on("remove-all", this.onRemoveAll);
  },
  beforeUnmount() {
    toastEventBus.off("add", this.onAdd);
    toastEventBus.off("remove", this.onRemove);
    toastEventBus.off("remove-all", this.onRemoveAll);
    Object.values(this.timers).forEach((timer) => clearTimeout(timer));
    this.timers = {};
  },
  methods: {
    onAdd(message) {
      if ((message?.group ?? null) !== this.group) return;
      const id = nextId++;
      const entry = { ...message, id };
      this.messages = [...this.messages, entry];

      if (!entry.sticky) {
        this.timers[id] = setTimeout(() => this.remove(id), entry.life ?? this.life);
      }
    },
    onRemove(message) {
      if (message && typeof message === "object" && "id" in message) {
        this.remove(message.id);
      }
    },
    onRemoveAll() {
      Object.values(this.timers).forEach((timer) => clearTimeout(timer));
      this.timers = {};
      this.messages = [];
    },
    remove(id) {
      this.messages = this.messages.filter((m) => m.id !== id);
      if (this.timers[id]) {
        clearTimeout(this.timers[id]);
        delete this.timers[id];
      }
    },
  },
};
</script>

// packages/react/src/toast/toast.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { toastStyleModule } from "./toast-style";

export interface UToastMessageOptions {
  severity?: "success" | "info" | "warn" | "error" | "secondary" | "contrast";
  summary?: string;
  detail?: string;
  /** Milliseconds before auto-dismissal; ignored when `sticky` is true. Defaults to the `UToast`'s own `life` prop (3000ms) when unset. */
  life?: number;
  /** When true, the message never auto-dismisses. */
  sticky?: boolean;
  /** Whether the message shows a manual close button. Defaults to true. */
  closable?: boolean;
  [extra: string]: unknown;
}

interface ToastEntry extends UToastMessageOptions {
  id: number;
}

let nextId = 0;

/** Imperative handle exposed via `ref` — matches real PrimeReact's own `show`/`clear` shape (real source's own `replace()`/`getElement()` excluded — smaller-than-upstream surface, disclosed). */
export interface UToastHandle {
  /** Queues one or more toast notifications — safe to call repeatedly for a stacked set of notifications. */
  show: (message: UToastMessageOptions | UToastMessageOptions[]) => void;
  /** Clears every queued/displayed message. */
  clear: () => void;
}

export interface UToastProps {
  position?:
    | "top-right"
    | "top-left"
    | "bottom-right"
    | "bottom-left"
    | "top-center"
    | "bottom-center"
    | "center";
  life?: number;
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `Toast` component (real
 * source: `components/lib/toast/Toast.js`/`ToastBase.js`). Confirmed
 * against real source: extends the bare `ComponentBase` tier (no CVA) — a
 * service-driven, transient-notification-stack overlay (spec §3.0's own
 * description). Real PrimeReact's own mechanism is genuinely different
 * from ConfirmDialog's `OverlayService.emit()` eventbus pattern
 * (investigated this task, not assumed): `Toast` exposes an imperative
 * `ref` handle (`useImperativeHandle` → `show`/`replace`/`remove`/`clear`,
 * `Toast.js` lines ~14-119) — callers hold a `ref` to the mounted
 * `<Toast>` and call `toastRef.current.show(...)` directly, not a
 * module-level event bus. This port keeps that same real ref-imperative
 * mechanism (`show`/`clear`, real source's own `replace`/`getElement`
 * excluded — smaller-than-upstream surface, disclosed) rather than forcing
 * Vue's `UToastService`/ConfirmDialog's eventbus shape onto React, per
 * this task's own instruction to investigate each framework's real
 * mechanism independently.
 *
 * Each queued message gets its own auto-dismiss timer (`life`, default
 * 3000ms, `sticky` disables it) — real source delegates this to a nested
 * `ToastMessage` sub-component; this port folds that responsibility into
 * `UToast` itself, same "smaller surface than upstream" precedent as
 * `UMessage`'s own plain-state-gated rendering (no enter/leave animation,
 * real source's own `CSSTransition`/`TransitionGroup` excluded).
 */
export const UToast = React.forwardRef<UToastHandle, UToastProps>(function UToast(
  { position = "top-right", life = 3000, className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "toast", styleModule: toastStyleModule });
  const [messages, setMessages] = React.useState<ToastEntry[]>([]);
  const timersRef = React.useRef(new Map<number, ReturnType<typeof setTimeout>>());

  const remove = React.useCallback((id: number) => {
    setMessages((prev) => prev.filter((m) => m.id !== id));
    const timer = timersRef.current.get(id);
    if (timer) {
      clearTimeout(timer);
      timersRef.current.delete(id);
    }
  }, []);

  const push = React.useCallback(
    (message: UToastMessageOptions) => {
      const id = nextId++;
      const entry: ToastEntry = { ...message, id };
      setMessages((prev) => [...prev, entry]);
      if (!entry.sticky) {
        const timer = setTimeout(() => remove(id), entry.life ?? life);
        timersRef.current.set(id, timer);
      }
    },
    [life, remove]
  );

  React.useImperativeHandle(
    ref,
    () => ({
      show: (message) => {
        const list = Array.isArray(message) ? message : [message];
        list.forEach(push);
      },
      clear: () => {
        timersRef.current.forEach((timer) => clearTimeout(timer));
        timersRef.current.clear();
        setMessages([]);
      },
    }),
    [push]
  );

  React.useEffect(() => {
    const timers = timersRef.current;
    return () => {
      timers.forEach((timer) => clearTimeout(timer));
      timers.clear();
    };
  }, []);

  return (
    <div className={[cx("root", { position }), className].filter(Boolean).join(" ")}>
      {messages.map((message) => (
        <div key={message.id} className={cx("message", { severity: message.severity })} role="alert" aria-live="assertive" aria-atomic="true">
          <div className={cx("messageContent")}>
            {message.summary && <div className={cx("summary")}>{message.summary}</div>}
            {message.detail && <div className={cx("detail")}>{message.detail}</div>}
          </div>
          {message.closable !== false && (
            <button
              type="button"
              className={cx("closeButton")}
              aria-label="Close"
              onClick={() => remove(message.id)}
            >
              &times;
            </button>
          )}
        </div>
      ))}
    </div>
  );
});
