// packages/vue/src/progress-bar/ProgressBar.vue
<template>
  <div
    :class="cx('root', { mode })"
    role="progressbar"
    aria-valuemin="0"
    aria-valuemax="100"
    :aria-valuenow="mode === 'determinate' ? value : undefined"
  >
    <div v-if="mode === 'determinate'" :class="cx('value')" :style="{ width: value + '%' }">
      <div v-if="showValue" :class="cx('label')">{{ value }}{{ unit }}</div>
    </div>
    <div v-else :class="cx('value')"></div>
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `ProgressBar` component (see
// .vendor-extracted/vue/progressbar/ProgressBar.vue). Confirmed against
// real source (all 3 frameworks): extends the bare `BaseComponent` tier
// (no v-model/writeValue) — a process-status indicator with
// `determinate` (numeric `value` + optional label) and `indeterminate`
// (animated, no value) modes.
//
// Deliberately excludes real source's `#content`/`#value` slot overrides
// and `color`/`valueStyle`/`valueClass` styling escape hatches — same
// "smaller surface than upstream" precedent as every sibling component.
import { createBaseProgressBar } from "./BaseProgressBar";

export default {
  name: "UProgressBar",
  extends: createBaseProgressBar(),
  inheritAttrs: false,
};
</script>

// packages/react/src/progress-bar/progress-bar.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { progressBarStyleModule } from "./progress-bar-style";

export interface UProgressBarProps {
  value?: number;
  showValue?: boolean;
  unit?: string;
  mode?: "determinate" | "indeterminate";
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `ProgressBar` component (real
 * source: `components/lib/progressbar/ProgressBar.js`). Confirmed against
 * real source (all 3 frameworks): extends the bare `ComponentBase` tier
 * (no CVA) — a process-status indicator with `determinate` (numeric
 * `value` + optional label) and `indeterminate` (animated, no value)
 * modes. Deliberately excludes real source's `displayValueTemplate`
 * render-prop override and `color`/`style`/`className` styling escape
 * hatches beyond the top-level `className` — same "smaller surface than
 * upstream" precedent as every sibling component.
 */
export const UProgressBar = React.forwardRef<HTMLDivElement, UProgressBarProps>(function UProgressBar(
  { value = 0, showValue = true, unit = "%", mode = "determinate", className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "progress-bar", styleModule: progressBarStyleModule });

  return (
    <div
      ref={ref}
      className={[cx("root", { mode }), className].filter(Boolean).join(" ")}
      role="progressbar"
      aria-valuemin={0}
      aria-valuemax={100}
      aria-valuenow={mode === "determinate" ? value : undefined}
    >
      {mode === "determinate" ? (
        <div className={cx("value")} style={{ width: `${value}%` }}>
          {showValue && (
            <div className={cx("label")}>
              {value}
              {unit}
            </div>
          )}
        </div>
      ) : (
        <div className={cx("value")} />
      )}
    </div>
  );
});
