// packages/react/src/breadcrumb/breadcrumb.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { breadcrumbStyleModule } from "./breadcrumb-style";
import type { UMenuItem } from "../menu";

export interface UBreadcrumbProps {
  /** An array of menuitems. */
  model?: UMenuItem[];
  /** MenuItem configuration for the home icon. */
  home?: UMenuItem;
  /** Defines a string that labels the home icon for accessibility. */
  homeAriaLabel?: string;
  /** Fired when an item is selected. */
  onItemClick?: (event: { originalEvent: React.SyntheticEvent; item: UMenuItem }) => void;
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `BreadCrumb` component (see
 * `.vendor-extracted/react/breadcrumb/BreadCrumb.js`). Renders a trail-of-
 * links `<nav><ol>` — an optional `home` item followed by `model` entries,
 * separated by a chevron `<li role="separator">` between each rendered
 * item.
 *
 * Real PrimeReact's `BreadCrumb` composes no `Menu`/`TieredMenu` — it's a
 * standalone, independent component (verified this task's Step 1 — no
 * import of `../menu`/`../tieredmenu` in `BreadCrumb.js`). This adaptation
 * follows the same independent shape: a plain component using
 * `useComponentBase`, not composing `UMenu`.
 *
 * `aria-current="page"` is applied per real PrimeReact's own `isCurrent()`
 * helper — matches the last item (and the home item) whenever its `url`
 * equals `window.location.pathname`.
 */
export const UBreadcrumb = React.forwardRef<HTMLElement, UBreadcrumbProps>(function UBreadcrumb(
  { model = [], home, homeAriaLabel, onItemClick, className },
  ref
) {
  const { cx } = useComponentBase({ componentName: "breadcrumb", styleModule: breadcrumbStyleModule });

  const isCurrent = (url?: string): "page" | undefined => {
    if (!url) return undefined;
    const path = typeof window !== "undefined" ? window.location.pathname : "";
    return url === path ? "page" : undefined;
  };

  const handleClick = (event: React.MouseEvent, item: UMenuItem) => {
    if (item.disabled) {
      event.preventDefault();
      return;
    }
    item.command?.({ originalEvent: event, item });
    onItemClick?.({ originalEvent: event, item });
    if (!item.url) {
      event.preventDefault();
      event.stopPropagation();
    }
  };

  const renderLink = (item: UMenuItem, key: string) => (
    <li className={cx("menuitem", { item: true })} key={key} data-u-disabled={String(!!item.disabled)}>
      <a
        href={item.url ?? "#"}
        className={cx("action")}
        aria-disabled={item.disabled}
        aria-current={isCurrent(item.url)}
        tabIndex={item.disabled ? -1 : undefined}
        onClick={(event) => handleClick(event, item)}
      >
        {item.icon && <span className={cx("icon")}>{item.icon}</span>}
        {item.label && <span className={cx("label")}>{item.label}</span>}
      </a>
    </li>
  );

  const renderSeparator = (key: string) => (
    <li className={cx("separator")} role="separator" key={key}>
      ›
    </li>
  );

  const visibleModel = model.filter((item) => item.visible !== false);

  return (
    <nav ref={ref} className={[cx("root"), className].filter(Boolean).join(" ")}>
      <ol className={cx("menu")}>
        {home && home.visible !== false && (
          <li className={cx("home")} data-u-disabled={String(!!home.disabled)}>
            <a
              href={home.url ?? "#"}
              className={cx("action")}
              aria-label={homeAriaLabel}
              aria-disabled={home.disabled}
              tabIndex={home.disabled ? -1 : undefined}
              onClick={(event) => handleClick(event, home)}
            >
              {home.icon && <span className={cx("icon")}>{home.icon}</span>}
              {home.label && <span className={cx("label")}>{home.label}</span>}
            </a>
          </li>
        )}
        {home && home.visible !== false && visibleModel.length > 0 && renderSeparator("sep_home")}
        {visibleModel.map((item, index) => (
          <React.Fragment key={item.label ?? index}>
            {renderLink(item, `item_${index}`)}
            {index < visibleModel.length - 1 && renderSeparator(`sep_${index}`)}
          </React.Fragment>
        ))}
      </ol>
    </nav>
  );
});

// packages/vue/src/breadcrumb/Breadcrumb.vue
<template>
  <nav :class="cx('root')">
    <ol :class="cx('list')">
      <template v-if="home && isVisible(home)">
        <li :class="cx('homeItem')">
          <a
            :href="home.routerLink ? undefined : home.url || '#'"
            :class="cx('itemLink')"
            :aria-label="homeAriaLabel"
            :aria-disabled="isDisabled(home) || undefined"
            :tabindex="isDisabled(home) ? -1 : 0"
            @click="onClick($event, home)"
          >
            <span v-if="home.icon" :class="[cx('itemIcon'), home.icon]" />
            <span v-if="home.label" :class="cx('itemLabel')">{{ home.label }}</span>
          </a>
        </li>
        <li v-if="model.length > 0" :class="cx('separator')" role="separator">›</li>
      </template>
      <template v-for="(item, i) in model" :key="(item.label || '') + i">
        <li v-if="isVisible(item)" :class="cx('item', { disabled: isDisabled(item) })">
          <a
            :href="item.routerLink ? undefined : item.url || '#'"
            :target="item.target"
            :class="cx('itemLink')"
            :aria-disabled="isDisabled(item) || undefined"
            :aria-current="i === lastIndex && isCurrent(item) ? 'page' : undefined"
            :tabindex="isDisabled(item) ? -1 : 0"
            :data-u-disabled="isDisabled(item)"
            @click="onClick($event, item)"
          >
            <span v-if="item.icon" :class="[cx('itemIcon'), item.icon]" />
            <span v-if="item.label" :class="cx('itemLabel')">{{ item.label }}</span>
          </a>
        </li>
        <li v-if="isVisible(item) && i !== lastIndex" :class="cx('separator')" role="separator">›</li>
      </template>
    </ol>
  </nav>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Breadcrumb`/`BreadcrumbItem`
// components (see `.vendor-extracted/vue/breadcrumb/Breadcrumb.vue`,
// `BreadcrumbItem.vue`). Renders a trail-of-links `<nav><ol>` — an
// optional `home` item followed by `model` entries, separated by a
// chevron `<li role="separator">` between each rendered item.
//
// Real PrimeVue's `Breadcrumb` (`extends BaseComponent`, no import of
// `primevue/menu`) is a standalone, independent component — it does NOT
// compose or wrap `Menu`; this adaptation follows that same independent
// shape, extending `createBaseComponent` directly (same tier `UMenu`
// itself uses via `createBaseMenu`), not `createBaseMenu`.
//
// Real upstream decomposes into `Breadcrumb.vue` (root) + a separate
// `BreadcrumbItem.vue` sub-component. This adaptation inlines item
// rendering into a single file instead, matching the decomposition-shape
// choice Ultimate's own Angular and React `UBreadcrumb` siblings already
// made for this same capability (both single-file, no separate item
// sub-component) — consistent cross-framework for this capability.
//
// Deliberately excludes upstream's passthrough (`pt`/`ptm`) system,
// per-item `templates`/slot projection (`item`/`separator`/`itemicon`
// custom templates), and separator-icon component — none of these appear
// in this task's scoped-down surface, matching the same reduction `UMenu`
// already applied to real PrimeVue's `Menu`.
//
// `aria-current="page"` is applied to the last rendered item's link
// whenever its `url` matches the current location path, adapted from
// real upstream's own `isCurrentUrl()` (`BreadcrumbItem.vue`) —
// `routerLink` (Vue Router's own `to`) is out of this project's smaller
// surface (real upstream checks both `to` and `url`; this adaptation
// checks `url` only, since `routerLink`-style navigation is not modeled
// here — matching the Angular/React siblings' own `isCurrent` intent
// adapted to Vue's own real `url`-only equivalent).
import { createBaseBreadcrumb } from "./BaseBreadcrumb";

export default {
  name: "UBreadcrumb",
  extends: createBaseBreadcrumb(),
  inheritAttrs: false,
  emits: ["item-select"],
  computed: {
    lastIndex() {
      return this.model.length - 1;
    },
  },
  methods: {
    isVisible(item) {
      return typeof item.visible === "function" ? item.visible() : item.visible !== false;
    },
    isDisabled(item) {
      return typeof item.disabled === "function" ? item.disabled() : !!item.disabled;
    },
    isCurrent(item) {
      if (!item.url) return false;
      return typeof window !== "undefined" && window.location.pathname === item.url;
    },
    onClick(event, item) {
      if (this.isDisabled(item)) {
        event.preventDefault();
        return;
      }
      if (!item.url) {
        event.preventDefault();
      }
      if (item.command) item.command({ originalEvent: event, item });
      this.$emit("item-select", { originalEvent: event, item });
    },
  },
};
</script>
