// packages/react/src/timeline/timeline.tsx
import * as React from "react";
import { useComponentBase } from "@ultimate/react-core";
import { timelineStyleModule } from "./timeline-style";

export interface UTimelineProps<T = unknown> {
  value: T[];
  align?: "left" | "right" | "top" | "bottom";
  layout?: "vertical" | "horizontal";
  content?: (item: T) => React.ReactNode;
  opposite?: (item: T) => React.ReactNode;
  marker?: (item: T) => React.ReactNode;
  className?: string;
}

/**
 * Ultimate-owned adaptation of PrimeReact's `Timeline` component (real
 * source: `components/lib/timeline/Timeline.js`/`TimelineBase.js`).
 * Confirmed against real source: extends the bare `ComponentBase` tier (no
 * CVA) — a display component visualizing a series of chained events, never
 * a form control.
 *
 * This port keeps real source's `value`/`align`/`layout` surface and its
 * three content slots (opposite/marker/content), realized here as render-
 * prop functions (`content`/`opposite`/`marker`) — React's established,
 * fully-controlled idiom for slot content, matching this package's own
 * `UPanel` header/footer render-prop precedent, rather than real source's
 * `content`/`opposite`/`marker` JSX-element-or-function props.
 */
export function UTimeline<T = unknown>({
  value,
  align = "left",
  layout = "vertical",
  content,
  opposite,
  marker,
  className,
}: UTimelineProps<T>): React.ReactNode {
  const { cx } = useComponentBase({ componentName: "timeline", styleModule: timelineStyleModule });

  return (
    <div className={[cx("root", { layout, align }), className].filter(Boolean).join(" ")}>
      {value.map((event, index) => (
        // eslint-disable-next-line react/no-array-index-key -- events have no stable identity in real source either
        <div key={index} className={cx("event")}>
          <div className={cx("eventOpposite")}>{opposite?.(event)}</div>
          <div className={cx("eventSeparator")}>
            {marker ? marker(event) : <div className={cx("eventMarker")} />}
            {index !== value.length - 1 && <div className={cx("eventConnector")} />}
          </div>
          <div className={cx("eventContent")}>{content?.(event)}</div>
        </div>
      ))}
    </div>
  );
}

// packages/vue/src/timeline/Timeline.vue
<template>
  <div :class="cx('root', { layout, align })">
    <div v-for="(event, index) of value" :key="index" :class="cx('event')">
      <div :class="cx('eventOpposite')">
        <slot name="opposite" :item="event"></slot>
      </div>
      <div :class="cx('eventSeparator')">
        <slot name="marker" :item="event">
          <div :class="cx('eventMarker')"></div>
        </slot>
        <div v-if="index !== value.length - 1" :class="cx('eventConnector')"></div>
      </div>
      <div :class="cx('eventContent')">
        <slot name="content" :item="event"></slot>
      </div>
    </div>
  </div>
</template>

<script>
// Ultimate-owned adaptation of PrimeVue's `Timeline` component (see
// .vendor-extracted/vue/timeline/Timeline.vue). Confirmed against real
// source (all 3 frameworks): extends the bare `BaseComponent` tier (no
// v-model/writeValue) — a display component visualizing a series of
// chained events, never a form control.
//
// This port keeps real source's `value`/`align`/`layout` surface and its
// three content slots (opposite/marker/content), realized here as scoped
// slots receiving `{ item: event }` — matching real PrimeVue's own
// `#opposite="slotProps"`/`#marker="slotProps"`/`#content="slotProps"`
// scoped-slot shape exactly (Option B: same mechanism, Ultimate-owned
// prop name `item` instead of upstream's `$implicit`-equivalent context).
import { createBaseTimeline } from "./BaseTimeline";

export default {
  name: "UTimeline",
  extends: createBaseTimeline(),
  inheritAttrs: false,
};
</script>
